---
title: "Considerations Touching Experimental Essays in General"
author: "Robert Boyle (1627-1691)"
output: tint::tintPdf
latexfonts: 
  - package: lato
    options: default
  - package: FiraMono
linkcolor: "0.3,0.3,0.6"
---

```{r setup, include=FALSE}
library(tint)
# invalidate cache when the package version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tint'))
options(htmltools.dir.version = FALSE)
```


A PROËMIAL ESSAY, WHEREIN, with some considerations touching EXPERIMENTAL ESSAYS in General, Is interwoven such an Introduction to all those written by the Author, as is necessary to be perused for the better understanding of them.

---

I Know not, Pyrohilus, whether what you will meet with in the ensuing Discourses will prove worthy of your taking notice of it: Yet I dare tell you, that if all my Endeavours to serve you were not Duties, I should think I might deserve your Thanks for venturing to write them for your sake. For I am sufficiently sensible both how unlearned I am, and in how learned an Age I presume to write: Nor has the great number of those escaped my Observation, who finding it a much easier task to censure Experimental Composures than to write such, endeavour to acquire the Title of Judicious, by condemning all things that themselves have not written, or thought on. And indeed, Pyrophilus, I had besides these, so many other discouraging Considerations in my Eye, whilst I was setting down the following Essays, that I should scarce have prosecuted a Design so full of trouble, and so unlikely by its success to make amends for it, if I had thought it free for the securing of my own Quiet and Credit, to suppress Observations which might prove serviceable to you, who having sufficiently conversed with Books, are now desirous to begin to converse with Things themselves. But I must confess, I look upon Experimental truths as Matters of so great concernment to Mankind, that in spight of the just sense I have of my own Disabilities, I am deterred from complying with those Inclinations and Motives that endear silence to me, by considering the Fate of him, who though he had less entrusted to him than any of his Companions, was yet severely punisht for burying his single Talent. And though, Pyrophilus, I could not without such reluctancy resolve to write, yet I found it much more uneasie to resolve to write so soon: For I could not but consider, that being yet but very young, not only in Years, but, what is much worse, in Experience, I have yet much more need to learn, than ability to teach; and I considered too, that after a man is grown somewhat acquainted with things themselves, and has taken some general notice of the Cognations, Differences, and Tendencies of their Properties, he may every day so much improve his Knowledge, that I am apt to think, that if God should be pleased to protract my Life a few years longer, I shall at the end of them be able to look upon what I have hitherto written with Pity, if not with Blushes. And I have often observed, that it is wont to happen in the productions of the Mind, as in those of the Body. For as those that apply themselves to Procreation too young, and before they have attained to their full vigour and strength, do generally both hinder their own growth, and become the Parents but of weak and short-lived Children; so they that too early, and before their Judgment and Experience be fully ripe, addict themselves to write Books, do commonly both hinder their own Proficiency in Knowledge, and write but immature, and therefore seldom lasting Treatises. Nor should I, Pyrophilus, have ever prevailed with my self to present you so early these Discourses, since by keeping them longer by me, I might easily by second Thoughts, and fresh Experiences be enabled to correct and enrich them, did not the frequent and dangerous distempers to which my very sickly Constitution has of late rendered me obnoxious, make me justly doubt, whether or no, if I should long forbear to write, Death would not sooner come than the expected Maturity of Age and Judgment. And though I had no such Consideration to move me to make hast to tender to you the ensuing Discourses, yet this would suffice to engage me to present them you with all their present defects; that if I should keep them till I can make them less unworthy of you, I must keep them till you are grown past the need of them.

And now that I have told you, Pyrophilus, both why I have written the ensuing Discourses, and why I keep them not by me long enough to present them you with fewer Imperfections, I suppose you will expect that I should next tell you why I have cast them into Essays, rather than into any other form. To satisfie you about this particular, Pyrophilus, I must freely acknowledge to you, that it has long seemed to me none of the least impediments of the real advancement of true Natural Philosophy, that men have been so forward to write Systems of it, and have thought themselves obliged either to be altogether silent, or not to write less than an entire body of Physiology: for from hence seem to have ensued not a few Inconveniences.

And first, when men by having diligently studied either Chemistry, Anatomy, Botanicks, or some other particular part of Physiology, or perhaps by having only read Authors on those Subjects, have thought themselves thereby qualified to publish compleat Systems of Natural Philosophy, they have found themselves by the nature of their undertaking, and the Laws of Method, engaged to write of several other things than those wherein they had made themselves Proficients, and thereby have been reduced, either idly to repeat what has been already, though perhaps but impertinently enough, written by others on the same Subjects, or else to say any thing on them rather than nothing, lest they should appear not to have said something to every part of the Theme which they had taken upon themselves to write of.

In the next place, the specious and promising Titles and comprehensive Method of these Systems have been often found to perswade unwary Readers, that all the parts of Natural Philosophy have been already sufficiently explicated, and that consequently it were needless for them to put themselves to trouble and charges in making further Enquiries into Nature, since others having already sufficiently made it their business to investigate and explicate Physiological Truths, our business needs now be no more than to learn what they have taught, and thankfully to acquiesce in it.

Nor has the Systematical way of writing been prejudicial only to the proficiency of some Readers, but also to the reputation of some Writers of Systematical Books. For it not unfrequently happens, that when a Writer, to vent some few peculiar Notions or Discoveries of his own, presumes to write a whole body of Philosophy, what is truly his own, though excellent in its kind, is either lost in the Crowd of the things he has borrowed from others, and so comes to be over-looked, or at least not sufficiently taken notice of, by the Reader; or else the unwelcome, and yet in such Composures scarce evitable, Repetition of many things that others had I know not how often written before, occasions the laying aside of the whole Book, as a Rhapsody of trite and vulgar Notions, scarce worth the perusing: and by this means the Author often loses the Reputation of his peculiar Notions, as well as the Reader the benefit of them; and that which would have made an excellent and substantial Essay, passes but for a dull and empty Book.

But the worst Inconvenience of all is yet to be mentioned, and that is, That whilst this Vanity of thinking men obliged to write either Systems or Nothing, is in request, many excellent Notions or Experiments are by sober and modest men suppressed, because such Persons being forbidden by their Judgment and Integrity to teach more than they understand, or assert more than they can prove, are likewise forbidden by Custome to publish their Thoughts and Observations, unless they were numerous enough to swell into a System. And indeed it may be doubted whether the Systematical Writers have not kept the world from much more useful Composures than they have presented it with. For there are very few men, if any at all, in the world, that are enriched with a competent stock of Experiments and Observations to make out clearly and solidly, I say not all the Phenomena of Nature, but all those that belong to Chemistry, Anatomy, or any such considerable subordinate Doctrine of Physiology. And those very men that are diligent and judicious enough to study prosperously any of those parts of Physiology, are obliged to spend so much time in the accurate Prosecution of that, and are wont to be thereby made so wary, and so thorowly acquainted with the difficulty of Physiological Investigations, that they will least of all men be forward to write Systems.

And what I say, Pyrophilus, of the inconveniences that have hitherto been observed to flow from mens forwardness to write entire bodies of Philosophy; may be in its degree applied to the practice of those that pretend to give us compleat accounts of Chemistry, or almost (I say almost) any other considerable and comprehensive part of Natural Philosophy: Though I deny not, that in such attempts which are much less difficult than the former, some Men have done Mankind considerable service, though they have not fully performed what the Titles of their Writings seem to promise. Nor am I so rigid as to be unwilling that from time to time some very knowing Writer should publish a System of Physiology, or any part of it, according to the best Authors and Observations of that time: For such a Work may be useful, partly, for the instructing of Youth in Schools and Academies; and partly, that men may have from time to time an Inventory of what has been already discovered, whereby the needless labour of seeking after known things may be prevented, and the progress of Mankind as to Knowledge might the better appear. But then it is to be wished that such Writings were not published but by very intelligent Persons, nor till some considerable improvement have been made in Knowledge since the last work of that Nature. Nor would I be thought to disallow such Writings of very Learned Men, as though they may bear very general Titles, yet are not published by their Authors as compleat Bodies or Systems of Physiology, but rather as general Principles (almost like the Hypotheses of Astronomers) to assist men to explicate the already-known Phenomena of Nature. For of such kind of Writings, if their Authors be (as for the most part they are) subtle and inquisitive men, there may be very good use, not so much by their gratifying the Intellect with the plausible account of some of Natures Mysteries; as because on the one side their Writers, to make good their new Opinions, must either bring New Experiments and Observations, or else must consider those that are known already after a new Manner, and thereby make us take notice of something in them unheeded before; and on the other side, the curiosity of Readers, whether they like or disapprove the Hypothesis proposed, is wont to be thereby excited to make trial of several things, which seeming to be Consequences of this new Doctrine, may by their proving agreeable or repugnant to Experiment either establish or overthrow it.

And that you may know, Pyrophilus, what kind of Writings I mean, I shall name to you the Learned Gassendus his little Syntagma of Epicuru's Philosophy, and that most ingenious Gentleman Monsr Des-Cartes his Principles of Philosophy. For though I purposely refrained, though not altogether from transiently consulting about a few Particulars, yet from seriously and orderly reading over those excellent (though disagreeing) Books, or so much as Sir Francis Bacon's Novum Organum, that I might not be prepossessed with any Theory or Principles till I had spent some time in trying what Things themselves would incline me to think; yet beginning now to allow my self to read those excellent Books, I find by the little I have read in them already, that if I had read them before I began to write, I might have enriched the ensuing Essays with many truths which they now want, and have explicated many things much better then I fear I have done. But of such Writers the number is yet (and will I fear always be) so small, that I shall not need to make many Exceptions when I treat of the usefulness of writing Books of Essays, in comparison of that of writing Systematically: Or at least, Pyrophilus, whilst I presume not to judge of other mens abilities, I hope it may be lawful for me to confess freely to you concerning my self, that I am very sensible of my being far from having such a stock of Experiments and Observations, as I judge requisite to write Systematically; and I am apt to impute many of the Deficiencies to be met with in the Theories and Reasonings of such great Wits as Aristotle, Campanella, and some other celebrated Philosophers, chiefly to this very thing, that they have too hastily, and either upon a few Observations, or at least without a competent number of Experiments, presumed to establish Principles, and deliver Axioms. For it very rarely otherwise happens, than that Theories that are grounded but upon few and obvious Experiments are subject to be contradicted by some such Instances as more free and diligent Enquiries into what of Nature is more abstruse, or even into the less obvious Qualities of things, are wont to bring to light. I remember, that being once at Leyden, I was brought to the Top of a Tower, where in a darkened room (such as is now used in many places to bring in the Species of external Objects) a Convex glass, applied to the only hole by which light was permitted to enter, did project upon a large white sheet of Paper, held at a just distance from it, a lively representation of many of the chief Buildings in the Town, all which upon the admission of more light into the room, by opening the Window, did immediately disappear. And methinks, Pyrophilus, that in many of the Philosophical Theories that have been formerly applauded, something not unlike this may be easily observed: for though, whilst they are looked on with such a weak and determinate degree of light, they may appear very artificial and well-proportioned Fabricks, yet they appear so but in that twilight, as it were, which is requisite to their conspicuousness. For if but a full light of new Experiments and Observations be freely let in upon them, the Beauty of those (delightful, but Phantastical) structures does immediately vanish.

And truly, Pyrophilus, if men could be perswaded to mind more the Advancement of Natural Philosophy than that of their own Reputations, 'twere not methinks very uneasie to make them sensible, that one of the considerablest services that they could do Mankind, were to set themselves diligently and industriously to make Experiments and collect Observations, without being over-forward to establish Principles and Axioms, believing it uneasie to erect such Theories as are capable to explicate all the Phenomena of Nature, before they have been able to take notice of the tenth part of those Phenomena that are to be explicated. Not that I at all disallow the use of Reasoning upon Experiments, or the endeavouring to discern as early as we can the Confederations, and Differences, and Tendencies of things: For such an absolute suspension of the exercise of Reasoning were exceeding troublesome, if not impossible. And as in that Rule of Arithmetick which is commonly called Regula falsi, by proceeding upon a conjecturally-supposed Number, as if it were that which we enquire after, we are wont to come to the knowledge of the true number sought for: so in Physiology it is somtimes conducive to the discovery of truth, to permit the Understanding to make an Hypothesis in order to the Explication of this or that difficulty, that by examining how far the Phenomena are, or are not, capable of being salved by that Hypothesis, the Understanding may even by its own Errors be instructed. For it has been truly observed by a great Philosopher, That Truth does more easily emerge out of Error than Confusion. That then that I wish for, as to Systems, is this, That men in the first place would forbear to establish any Theory, till they have consulted with (though not a fully competent number of Experiments, such as may afford them all the Phenomena to be explicated by that Theory, yet) a considerable number of Experiments in proportion to the comprehensiveness of the Theory to be erected on them. And in the next place, I would have such kind of superstructures looked upon only as temporary ones, which though they may be preferred before any others, as being the least imperfect, or, if you please, the best in their kind that we yet have, yet are they not to entirely be acquiesced in, as absolutely perfect, or uncapable of improving Alterations. 

It were very possible, Pyrophilus, to let you see that all that has been said to recommend to you that form of Writing which (in imitation of the French) we call Essayes, is but a part of what may be pertinently said to the same purpose. But because this Introductory Discourse it self is to be but an Essay, not a Book, I dare not long insist upon the Advantages of this sort of Discourses. Only because I think that if I could engage you, Pyrophilus, and such other ingenious Persons, to cast their Physiological Observations and Reflexions into Experimental Essayes, I should thereby do real Learning no trifling service, by bringing so useful a way of writing into the request it deserves; Upon this consideration, I say, I must beg leave to represent to you this great Conveniency of Essayes, That as in them the Reader needs not be clogged with tedious Repetitions of what others have said already, so the Writer, having for the most part the Liberty to leave off when he pleases, is not obliged to take upon him to teach others what himself does not understand, nor to write of any thing but of what he thinks he can write well. And if such Essayes be but as they should be competently stocked with Experiments, it is the Readers own fault if he be not a Learner by them: for indeed when a Writer acquaints me only with his own Thoughts or Conjectures, without enriching his discourses with any real Experiment or Observation, if he be mistaken in his Ratiocination, I am in some danger of erring with him, and at least am like to lose my time, without receiving any valuable Compensation for that great loss: but if a Writer endeavours, by delivering new and real Observations or Experiments, to credit his Opinions, the Case is much otherwise; for let his Opinions be never so false, his Experiments being true, I am not obliged to believe the former, and am left at liberty to benefit my self by the later; and though we have erroneously superstructed upon his Experiments, yet the foundation being solid, a more wary builder may be very much furthered by it in the erection of more judicious and consistent Fabricks: such a Writer, if I be not wanting to my self, will certainly teach me useful Truths, and if it be not my fault, he can lead me into no errors; and oftentimes the very Experiments that he delivers, besides that they may be applicable to many other purposes unthought of by him, may be either sufficient or at least helpful to the very discovery of the erroneousness of the Opinions they are alledged to countenance: and I make account that a man that gives me, together with his conjectures (though erroneous) in matters of Physiology, some noble Experiment or Observation by which he pretends to verifie them, does me no greater injury than Galileo upon his first Invention of the Telescope would have done an Astronomer, if he had told him, that he had discovered in Heaven those imaginary new Stars which a late Mathematician has fancied himself to have descried there, and at the same time had made him a Present of an excellent Telescope, with expectation that thereby the Receiver should be made of the Giver's Opinion; for by the help of his Instrument the Astronomer might not only make many useful Observations in the Sky, and perhaps detect new Lights there, but discern also his mistake that gave it him.

After what has been said, Pyrophilus, of the Usefulness of experimental Essays, we must proceed to say something concerning the Manner of writing them: but because you will also expect to receive some account of the ensuing Discourses, I shall not treat of those two Subjects apart, but, in discoursing of the following Essays, shall take occasion to acquaint you with part of my thoughts concerning such kind of Composures in general, the other Considerations belonging to the same Subject being already upon several Occasions dispersed among, and to be met with in, the ensuing Discourses themselves.

And first, as for the style of our experimental Essays, I suppose you will readily find that I have endeavoured to write rather in a Philosophical than a Rhetorical strain, as desiring that my expressions should be rather clear and significant, than curiously adorned: For, to a subject of the serious and important Nature of Physiology, that saying may unquestionably be applied, Ornari res ipsa negat, contenta doceri. And certainly in these Discourses, where our design is only to inform Readers, not to delight or perswade them, Perspicuity ought to be esteemed at least one of the best Qualifications of a style, and to affect needless Rhetorical Ornaments in setting down an Experiment, or explicating something abstruse in Nature, were little less improper than it were (for him that designs not to look directly upon the Sun it self) to paint the Eye-glasses of a Telescope, whose clearness is their Commendation, and in which even the most delightful Colours cannot so much please the eye as they would hinder the sight. And that it may not be suspected, that those that would not have it requisite to imploy a florid style in treating of Philosophical Subjects, do but in their own excuse deny the necessity of such Rhetorical Embellishments as they are not able to afford their Composures, give me leave to subjoyn, that it was not an unpolished Naturalist, but that Prince of Orators, Cicero himself, who made this studious Declaration, *Omne (says he) quod de re bona dilucidè dicitur, praeclarè mihi dici videtur: istiusmodi autem res velle ornatè dicere, puerile est; planè autem et perspicuè expedire posse, docti et intelligentis Viri.* But I must not suffer my self to slip unawares into the Common place of the unfitness of too spruce a style for serious and weighty matters; and yet I approve not that dull and insipid way of writing which is practised by many Chemists, even when they digress from Physiological Subjects: for though a Philosopher need not be sollicitous that his style should delight its Reader with his Floridnesse, yet I think he may very well be allowed to take a Care that it disgust not his Reader by its Flatness, especially when he does not so much deliver Experiments or explicate them, as make Reflections or Discourses on them; for on such Occasions he may be allowed the liberty of recreating his Reader and himself, and manifesting that he declined the Ornaments of Language, not out of Necessity, but Discretion, which forbids them to be used where they may darken as well as adorn the Subject they are applied to. Thus (to resume our former Comparison) though it were foolish to colour or enamel upon the glasses of Telescopes, yet to gild or otherwise embellish the Tubes of them, may render them more acceptable to the Users, without at all lessening the Clearness of the Object to be looked at through them.

And as for Exotick Words and Terms borowed from other Languages, though I expect that Persons not conversant in the Philosophical Composures written (especially of late) in our Language will be apt to suspect me for the willing Author of many new Words and Expressions, yet as for you, Pyrophilus, who peruse other then Moral, Theological, and Historical Books in English, and find how much use is made in them of Exotick Terms, I hope you will find that I have not at all affected them, but have rather studiously declined the use of those which Custom has not rendered familiar, unlesse it be to avoid the frequent and unwelcome Repetition of the same word, (so troublesome to the Ear, and so much forbidden by Orators) or for some peculiar significancy of some such Word, whose Energy cannot be well expressed in our Language, at least without a tedious Circumlocutioo. And in such cases, Pyrophilus, I suppose a Writer may be allowed to use Exotick Terms, especially when Custom has not only Denizoned them, but brought them into request. For as in the Fashions of Clothes, though perhaps Fools begin them, yet Wise men, when they are once generolly received, scruple not to follow them, because then obstinately to decline them would be as ridiculously singular as at first it would have been to begin them: so in Exotick Words, when Custom has once made them familiar and esteemed, scrupulously to decline the use of them may be as well a fault, as needlesly to imploy them: For it is not the Use but the Affectation of them that is unworthy a Philosopher. And from the latter of those I hope I have kept my self far enough: For I should think my self guilty of a very Childish vanity, if the use I made of Languages were so to write as to be the less understood. But besides the unintentional deficiencies of my style, I have knowingly and purposely transgressed the Laws of Oratory in one particular, namely, in making sometimes my Periods or Parentheses over-long: for when I could not within the Compass of a regular Period comprise what I thought requisite to be delivered at once, I chose rather to neglect the Precepts of Rhetoricians, than the mention of those things which I thought pertinent to my Subject, and useful to you, my Reader. And for this fault, Pyrophilus, since I have made my self guilty of it but for your sake, I think I ought to obtain your pardon at least as easily as my own, since barely to keep you from losing any thing that I conceived might be serviceable to you, I knowingly expose my style to be censured as disproportionate to it self.

The next thing, Pyrophilus, of which I am to give you an account, is, why I have in the ensuing Essays delivered many Experiments and Observations, which may seem slight and easie, and some of them obvious also, or else perhaps mentioned by others already. To satisfie you about this, I must inform you that many of the Particulars which we are now considering, were in my first Design collected in order to a Continuation of the Lord Verulam's Sylva Sylvarum, or Natural History. And that my intended Centuries might resemble his, to which they were to be annexed, it was exquisite that such kind of Experiments and Observations as we have been newly speaking of, should make up a considerable part of them. And indeed it were to be wished, that such inquisitive Persons as cannot be at the Charge, or have not the opportunity, of making new Experiments, would busie themselves, as they have opportunity, in industriously collecting and carefully setting down the Phenomena to be met with without the Assistance of new Experiments, especially such particulars as seem either to be of moment in order to the hinting or Confirmation of some Considerable Truth, or to the Detection of some Applauded Error, or else to have bin, though obvious enough, yet little taken notice of. For I am confident that very much may be done towards the Improvement of Physiology by a due Consideration of and reflexion on the obvious Phenomena of Nature, and those things which are almost in every bodies power to know, if he please but seriously to heed them; and I make account that attention alone might quickly furnish us with one half of the History of Nature, as well as industry is requisite, by new Experiments, to enrich us with the other. And therefore I confess I think my self beholding to him that first makes me take notice of what I might easily have known, but heeded not before; it not seldom happening, that we are prejudiced by, though we do not complain of that ignorance from which we might relieve our selves, if we did but diligently turn our eyes to the Observations wherewith even neighbouring and familiar Objects would, if duly consulted, present us. But I digress, and therefore must step back into the way, and tell you, that the reasons why I first designed the Narrative of what I had tried and observed for a Continuation of Sir Francis Bacons Natural History, you will meet with in my Preface to that specimen of the intended Continuation, which I have given in those of my Essays that treat Of Promiscuous Experiments: and the reason why I have since declined that succinct way of Writing, is, for the sake of Pyrophilus, that I might have, in a more free and uncircumscribed way of discoursing, a greater Liberty to insist on and manifesf the Reasonableness of such Animadversions as I thought seasonable for a Person, who, though a great Proficient in the other parts of Philosophy, is but a Beginner in Experimental Learning. And the second Reason why I have often made use of seemingly slight Experiments, is, because such are more easily and cheaply tried, and they being alledged for the most part to prove some Assertion, or credit some Admonition, I thought their Easiness or Obviousness fitter to recommend them, than depretiate them; and I judged it somewhat unkind, or at least indiscreet, to refer you most commonly for proof of what I delivered, to such tedious, such difficult, or such intricate Processes, as either You can scarce well make, unless You be already what I desire my Experiments should help to make You, a skilful Chemist; or else are as difficult to be well judged, as the truth they should discover is to be discerned. I was also hopeful that the Easiness of many things inviting you to make tryal of them, and keeping You from being disappointed in Your Expectations, the success of Your first attempts would incourage You to make tryal also of more nice and difficult Experiments. And till You have tried them, do me the right to think that I deal not unsincerely with You.

The Reasons of my having many times recorded Experiments which You may have formerly met with, and perchance even in Printed Books, I have elsewhere deduced in a peculiar Discourse on that Subject: and therefore shall now only add, that by reason of my being as yet a stranger to the German Tongue, wherein the most and best Chemical Books are said to be written, I may have set down many Chemical Experiments and Observations that are extant already in that Hermetical Language, (if I may so call it) without having had them from their Dutch Publishers, or so much as dreamed of their having been divulged by any man. I have likewise in my Preface to the Essays that you will meet with under the Title of Promiscuous Experiments, given You an account why I have not refrained from mentioning many things which may seem very slight, because very obvious: And I have long had thoughts to inform You in an intire Discourse to be written on purpose, why I think that even the trivial, and therefore slighted, truths of Physiology ought not to be despised. And for my own part, I shall not scruple to confess to You, that I disdain not to take Notice even of Ludicrous Experiments, and think that the Plays of Boys may sometimes deserve to be the Study of Philosophers: For as when we go a Hunting, though the flight of the Hare and the pursute of the Dogs be to us but sport and recreation, yet the Beasts themselves are extreamly earnest, the one to save his threatned life by flight, and the other to overtake his desired Prey; so Nature acts very seriously in all the other things that we make sports with, and is in very good earnest, whether we Men be so or no.

Perhaps you will wonder, Pyrophilus, that in almost every one of the following Essays I should speak so doubtingly, and use so often, Perhaps, It seems, it is not improbable, and such other expressions as argue a diffidence of the truth of the Opinions I incline to, and that I should be so shy of laying down Principles, and sometimes of so much as venturing at Explications. But I must freely confess to you, Pyrophilus, that having met with many things of which I could give my self no one probable cause, and some things of which several Causes may be assigned so differing, as not to agree in any thing unless in their being all of them probable enough, I have often found such Difficulties in searching into the Causes and Manner of things: and I am so sensible of my own Disability to surmount those Difficulties, that I dare speak confidently and positively of very few things, except of Matters of fact. And when I venture to deliver any thing by way of Opinion, I should, if it were not for meer shame, speak yet more diffidently than I have been wont to do. It is not that I at all condemn the Practice of those Inquisitive Wits that take upon them to explicate to us even the abstrusest Phenomena of Nature: For I am so far from censuring them, that I admire them when their Endeavours succeed, and applaud them even where they do but fairly attempt. But I think it is fit for a man to know his own Abilities and Weaknesses, and not to think himself obliged to imitate all that he thinks fit to praise. I know also that the way to get Reputation, is, to venture to explicate things, and promote Opinions: For by that course a Writer shall be sure to be applauded by one sort of men, and be mentioned by many others; whereas by the way of Writing to which I have condemned my self, I can hope for little better among the more daring and less considerate sort of men, should you show them these Papers, than to pass for a Drudge of greater Industry than Reason, and fit for little more than to collect Experiments for more rational and Philosophical heads to explicate and make use of. But I am content, provided Experimental Learning be really promoted, to contribute even in the least plausible Way to the Advancement of it, and had rather not only be an Underbuilder, but even dig in the Quarries for Materials towards so useful a Structure, as a solid body of Natural Philosophy, than not do something towards the Erection of it. Nor have my thoughts been altogether idle and wanting to themselves, in framing Notions, and attempting to devise Hypotheses, which might avoid the deficiencies observed in other mens Theories and Explications: but I have hitherto, though not always, yet not unfrequently, found that what pleased me for a while, as fairly comporting with the Observations on which such Notions were grounded, was soon after disgraced by some further or new Experiment, which at the time of the framing of those Notions was unknown to me, or not consulted with. And indeed I have the less envied Many (for I say not All) of those Writers who have taken upon them to deliver the Causes of things, and explicate the Mysteries of Nature, since I have had opportunity to observe how many of their Doctrines, after having been for a while applauded and even admired, have afterwards been confuted by the discovery of some new Phenomenon in Nature, which was either unknown to such Writers, or not sufficiently considered by them. For I have found it happen as well to many others (that have publisht their Opinions) as to me (who have been more private in my Guesses) in our Theories built on either too obvious or too few Experiments, what is wont to happen to the Falsifiers of Coyn: for as Counterfeit pieces of Money will endure some of them One Proof, as the Touch-stone, others Another, as Aqua fortis, some a third, as the Hammer or the Scales, but none of them will endure All proofs; so the Notions I mention (in which sort I fear too great a part of those hitherto extant may be comprized) may agree very fairly with this or that or the other Experiment, but being made too hastily, and without Consulting a competent number of them, it is to be feared that there may still after a while be found one or other, (if not many) their Inconsistency with which will betray and discredit them.

I have notwithstanding all this on some occasions adventured to deliver my Opinion, not that I am very confident of being less subject to erre in those particulars than in any of the others wherein I have refrained from interposing any Conjecture, but because I would manifest to You, that I scruple not to run the same venture with those incomparably better Naturalists, that have thought it no disgrace in difficult matters rather to hazard the being sometimes mistaken, than not to afford Inquisitive Persons their best Assistance towards the Discovery of Truth.

And because, Pyrophilus, in the Reasons and Explications I offer of Natural Effects, I have not for the most part an immediate recourse to the Magnitude, Figure, and Motion of Atoms, or of the least Particles of Bodies, I hold it not unfit to give You here some account of this Practice, not so much for the sake of those few Passages in my Essays that may be concerned in it, as for that of many Learned men, especially Physicians, whose useful Writings begin to be undervalued, and are in danger to be despised, by an Opinion taken up from the mis-understood Doctrine of some eminent Atomists, as if no speculations in Natural Philosophy could be rational, wherein any other causes of things are assigned than Atoms and their Properties. I consider then, that generally speaking, to render a reason of an Effect or Phenomenon, is to deduce it from somthing else in Nature more known than it self, and that consequently there may be many kinds of Degrees of Explication of the same thing. For although such Explications be the most satisfactory to the Understanding, wherein it is shown how the effect is produced by the more primitive and Catholick Affection of Matter, namely, bulk, shape and motion, yet are not these Explications to be despised, wherein particular effects are deduced from the more obvious and familiar Qualities or states of Bodies, such as Heat, Cold, Weight, Fluidity, Hardness, Fermentation, etc. Though these themselves do probably depend upon those three universal ones formerly named. For in the search after Natural Causes, every new measure of Discovery does both instruct and gratifie the Understanding, though I readily confess, that the nearer the discovered Causes are to those that are highest in the scale or series of Causes, the more is the Intellect both gratified and instructed.

I think it therefore very fit and highly useful, that some speculative Wits well versed in Mathematical Principles and Mechanical Contrivances, should employ themselves in deducing the chiefest Modes or Qualities of Matter, such as are Heat, Cold, etc. and the States or conditions of it, (if we think fit to distinguish these from its Qualities) as fluid, firm, brittle, flexible, and the like, from the above-mentioned most primitive and simple Affections thereof. And I think the Common-wealth of Learning exceedingly beholden to those Heroick Wits that do so much as plausibly perform something in this kind. But I think too, we are not to despise all those Accounts of particular Effects which are not immediately deduced from those primitive Affections of either Atoms or the insensible Particles of Matter, but from the familiar, though not so universal, Qualities of things, as cold, heat, weight, hardness, and the like. And perhaps it would be none of the least advantages which would accrue to Naturalists from a satisfactory explication of such Qualities by the most primitive and simple ones, that it would much shorten the explication of particular Phenomena: For though there be many things in Nature that may be readily enough made out by the Size, Motion, and Figure of the small Parts of Matter, yet there are many more that cannot be well explained without a great deal of Discourse, and many successive Deductions of one thing from another, if the purposed effect must be deduced from such primary and Universal Causes; whereas if we be allowed to take the Notions of Cold, Heat, and the like Qualities for granted, the explications and proofs may be much more compendiously made. He gives some Reason why Stones and Iron and all other heavy Bodies will swim in Quick-silver, except Gold, which will sink in it, that teaches, that all those other Bodies are in specie (as they speak) or bulk for bulk, lighter than Quick-silver, whereas Gold is heavier. He, I say, may be allowed to have rendered a Reason of the thing proposed, that thus refers the Phenomenon to that known Affection of almost all Bodies here below, which we call Gravity, though he do not deduce the Phenomenon from Atoms, nor give us the cause of Gravity, as indeed scarce any Philosopher has yet given us a satisfactory Account of it. So if it be demanded, why, if the sides of a blown Bladder be somewhat squeezed between ones hands, they will, upon the removal of that which compressed them, fly out again, and restore the Bladder to its former figure and dimensions, it is not saying nothing to the purpose, to say that this happens from the spring of those Aerial Particles wherewith the Bladder is filled, though he that says this be not perhaps able to declare whence proceeds the Motion of Restitution, either in a Particle of compressed Air, or any other bent spring.

And as for the Reasons of things assigned by Physicians, they must be most of them despised, unless we will allow of such explications as deduce not things from Atoms or their Affections, but only either from secondary Qualities, or from the more particular Properties of Mixt Bodies. If a Physician be asked why Rhubarb does commonly cure Loosenesses, he will probably tell you as a Reason, that Rhubarb is available in such Diseases, because it has both a Laxative virtue, whereby it evacuates Choler, and such other bad humours as are wont in such cases to be the peccant Matter, and an astringent Quality, whereby it afterwards arrests the Flux: But if you further ask him the Reason why Rhubarb purges, and why it purges Choler more than any other humour, it is ten to one he will not be able to give you a satisfactory answer. And indeed, not only the manner whereby Purgative Medicines Work, but those other Properties whereby some Bodies are Diuretick, others Sudorifick, others Sarcotick, etc. are not I fear so easie to be intelligibly made out as men imagine, and yet a skilful Physician would justly think himself wronged, if the Reasons he renders of things in his own Profession were denied the Name of Reasons, because made without recourse to Atomical Principles. And indeed, there are oftentimes so many subordinate Causes between particular Effects and the most General Causes of things, that there is left a large field wherein to exercise Mens Industry and Reason, if they will but solidly enough deduce the Properties of things from more general and familiar Qualities, and also intermediate Causes (if I may so call them) from one another. And I am the more backward to despise such kind of Reasons, because I elsewhere declare, that there are Some (for I do not say, Many) things, as particularly the Origine of Local Motion, of which even by the Atomical Doctrine no Physical Cause can well be rendered; since either such things must be ascribed to God, who is indeed the true, but the supernatural Cause of them, or else it must be said, (as it was by the old Epicureans) that they did ever belong to Matter, which, considering that the Notion of Matter may be compleat without them, is not to give a Physical efficient cause of the things in Question, but in effect to confess that they have no such Causes. But of this elsewhere more.

In the mean time, that you may not be drawn away to undervalue such Writers as I have been pleading for, nor think you ought to refrain from writing what occurs to you, though true and useful, unless you deduce it, or at least can do so, from the Epicurean Notions, I shall here briefly represent to you, (what perhaps you will not hereafter think a despicable suggestion) that there are two very distinct Ends that Men may propound to themselves in studying Natural Philosophy. For some Men care only to Know Nature, others desire to Command Her: or to express it otherwise, some there are who desire but to Please themselves by the Discovery of the Causes of the known Phenomena, and others would be able to produce new ones, and bring Nature to be serviceable to their particular Ends, whether of Health, or Riches, or sensual Delight. Now as I shall not deny but that the Atomical, the Cartesian, or some such Principles, are likely to afford the most of satisfaction to those speculative Wits that aim but at the knowledge of Causes; so I think that the other sort of men may very delightfully and  successfully prosecute their ends, by collecting and making Variety of Experiments and Observations, since thereby learning the Qualities and Properties of those particular Bodies they desire to make use of, and observing the power that many Chemical Operations, and other ways of handling Matter, have of altering such Bodies, and varying their effects upon one another, they may by the help of Attention and Industry be able to do many Things, some of them very Strange, and more of them very Useful in humane life. When a Gunner or a Souldier employs Gun-powder, it is not necessary that he should consider, or so much as know, of what and of how many Ingredients (much less of what kind of Atoms) it is made, and the proportion and manner wherein they are mingled; but the Notice Experience gives him of the power of that admirable Concrete, as it is made up and brought to his hands, suffices to enable him to perform things with it, that nothing but their being common and unheeded can keep from being admired. The Physician that has observed the Medicinal vertues of Treacle, without knowing so much of the names, much less the Nature of each of the sixty and odd Ingredients whereof it is compounded, may cure many Patients with it. And though it must not be denied, that it is an advantage as well as a satisfaction, to know in general how the Qualities of things are deducible from the primitive Affections of the smallest parts of Matter, yet whether we know that or no, if we know the Qualities of this or that Body they compose, and how it is disposed to work upon other Bodies, or be brought on by them, we may, without ascending to the Top in the series of Causes, perform things of great Moment, and such as without the diligent Examination of particular Bodies would, I fear, never have been found out à priori even by the most profound Contemplators. We see that the Artificers that never dreamed of the Epicurean Philosophy, have accommodated Mankind with a Multitude of useful Inventions, And Paracelsus, who (besides that he seems none of the most piercing and speculative Wits) sure had little recourse to Atomical Notions, if he ever so much as heard of them, was able to perform some things that were truly admirable, besides those he vainly boasted of; as may appear not only by what I elsewhere represent, but by what Oporinus himself (as severely as he otherwise writes against his deserted Master) confesses he saw of the stupendous cures which Paracelsus wrought with his famous Laudanum, (whatever he made it of.) But we need not go far to find a noble Example to our present purpose, since we see that the bare making of tryals with the Load-stone, and Irons touched by it, though the Experimentors were ignorant (as some fear we yet are) of the true and first Causes of Magnetical Phenomena, have produced Inventions of greater use to Mankind, than were ever made by Leucippus, or Epicurus, or Aristotle, or Telesius, or Campanella, or perhaps any of the speculative Devisers of new Hypotheses, whole Contemplations aiming for the most part but at the solving, not the encreasing or applying, of the Phenomena of Nature, it is no wonder they have been more ingenious than fruitful, and have Hitherto more delighted than otherwise benefitted Mankind: I say Hitherto, because though Experience warrants me so to speak now, yet I am not unwilling to think that Hereafter, and perhaps in no long time, when Physiological Theories shall be better established, and built upon a more competent number of Particulars, the Deductions that may be made from them may free them from all Imputation of Barrenness. But of these things I otherwhere (though not as I remember in any of the following Essays) more fully discourse.

And therefore I shall now resume the Subject that occasioned this long Excursion, and add to what I said in excuse of my venturing sometimes to deliver something as my Opinion in difficult or controverted cases, that I must declare to you, Pyrophilus, that as I desire not my Opinions should have more Weight with you than the Proofs brought to countenance them will give them, so you must not expect that I should think my self obliged to adhere to them any longer than those Considerations that first made me embrace them shall seem of greater Moment than any that I can meet with in opposition to them. For Aristotle spoke like a Philosopher, when to justifie his Dissent from his Master Plato, he said[^1] among other things, That for the sake of Truth, men (especially being Philosophers) ought to overthrow even their own Tenents ("Still perhaps it would appear desirable, and indeed it would seem to be obligatory, especially for a philosopher, to sacrifice even one's closest personal ties in defense of the truth.")[^2] And though for a man to change his opinions, without seeing more reason to forsake them than he had to assent to them, be a Censurable Levity and Inconstancy of mind; yet to adhere to whatever he once took for truth, though by Accession of more light he discover it to be erroneous, is but a proud Obstinacy very injurious to Truth, and very ill becoming the sense we ought to have of humane frailties. And it ought to be esteemed much less disgraceful to quit an Error for a Truth, than to be guilty of the Vanity and Perverseness of believing a thing still, because we once believed it. And certainly, till a Man is sure he is infallible, it is not fit for him to be unalterable.

[^1]: [original footnote] Ethic. Nicom. 1, I. cap 6.

[^2]: Original was in Greek. See http://www.perseus.tufts.edu/hopper/text?doc=urn:cts:greekLit:tlg0086.tlg010.perseus-eng1:1096a.

You will easily discern, Pyrophilus, that I have purposely in the ensuing Essays refrained from swelling my Discourses with solemn and elaborate Confutations of other mens Opinions, unless it be in some very few Cases, where I judged that they might prove great impediments to the Advancement of Experimental Learning; and even such Opinions I have been wary of medling with, unless I supposed I could bring Experimental Objections against them. For it is none of my Design to engage my self with or against any one Sect of Naturalists, but barely to invite you to embrace or refuse Opinions as they are consonant to Experiments, or clear Reasons deduced thence, or at least analogous thereunto, without thinking it yet seasonable to contend very earnestly for those other Opinions which seem not yet determinable by such Experiments or Reasons. And indeed, to allude to our former Comparison, I would endeavour to destroy those curious but groundless structures that men have built up of Opinions alone, by the same way (and with as little Noise) by which such fantastical structures as those I mentioned to have seen at Leyden may be demolished. To destroy which 'twere needless to bring battering Engines, since nothing is requisite to that effect but an encrease of Light. And Experience has shown us, that many very plausible and radicated Opinions, such as that of the Unhabitableness of the Torrid Zone, of the Solidity of the Celestial part of the World, of the Blood's being conveyed from the Heart by the Veins (not the Arteries) to the outward parts of the body, are generally grown out of request, upon the appearing of those new Discoveries with which they are inconsistent, and would have been abandoned by the Generality of Judicious Persons, though no man had made it his business purposely to write Confutations of them: so true is that Vulgar saying, that *Rectum est Index sui et Obliqui.*

But when at any time, Pyrophilus, I have been induced to oppose others, as I have not denied my self the freedom that is requisite unto Loyalty to Truth, so I have endeavoured to use that Moderation and Civility that is due to the persons of deserving Men. And therefore you shall find me not only in one Essay oppose an Author whom in another I applaude, but sometimes you may find me commending a Writer in the very same Page, perhaps, where I am endeavouring to disprove his Opinions: For I love to speak of Persons with Civility, though of Things with Freedom. Nor do I think it reasonable, either that any mans Reputation should protect his Errors, or that the Truth should fare the worse for his sake that delivers it. And as for the (very much too common) Practice of many, who write, as if they thought, railing at a mans Person, or wrangling about his Words, necessary to the Confutation of his Opinions; besides that I think such a quarrelsome and injurious way of writing does very much misbecome both a Philosopher and a Christian, methinks it is as unwise, as it is provoking. For if I civilly endeavour to reason a man out of his Opinions, I make my self but one work to do, namely, to convince his Understanding: but if in a bitter or exasperating way I oppose his Errors, I encrease the Difficulties I would surmount, and have as well his Affections against me as his Judgment: and it is very uneasie to make a Proselyte of him that is not only a Dissenter from us, but an Enemy to us. And that which makes me the more dislike the bitter way of disputing which I am reprehending, is, that I have often observed, that though one of the Disputants alone be at first in the fault, yet the other is most commonly drawn to share in the Guilt, though to contract it he must imitate his Adversary. For as a mad Dog by biting others is wont to make those he bites run mad like himself, and do promiscuous Mischief; so these so provoking Writers are wont to enrage those they offend, and infect them also with their own virulent distemper. But, Pyrophilus, when I speak of dealing respectfully with those I dissent from, I would be understood of such as have well deserved of Experimental Learning, or at least been candid and sober inquirers after Truth. For, as I think that it would much discourage any prudent Person from venturing to communicate what he thinks he knows to the World, to find that an Error proceeding from humane Weakness, or the Darkness and Abstrusity of things, seldom escapes being detected without being made matter of disgrace or reproach to the Author: so on the other side, when vain Writers, to get themselves a name, have presumed to obtrude upon the credulous World such things, under the Notion of Experimental Truths, or even great Mysteries, as neither themselves ever took the pains to make tryal of, nor received from any credible Persons that professed themselves to have tried them; in such cases, I see not how we are obliged to treat Writers that took no pains to keep themselves from mistaking or deceiving, nay, that cared not how they abuse us to win themselves a name, with the same respect that we owe to those, who though they have missed of the Truth, believed they had found it, and both intended to deliver It, and took some (though not prosperous) pains that they might convey nothing else to us.

I fear it will be requisite, Pyrophilus, to tell you why in some of the following Essays you will meet with many Passages transcribed out of other Authors, and in some very few or none at all. And therefore to give you first a short Account of the Particular mentioned last, I must mind you, that 'twas most suitable both to my Humor and Design to deliver only those things wherewith my own Observations, or Tryals, or Thoughts, had furnished me, without troubling you with the Repetition of those things which had been delivered by others already; those kind of Repetitions, unless they be made upon some such grounds as we shall presently mention, seeming to me to be as vainly as ambitiously affected by many Writers, and being deservedly troublesome to Judicioas Readers, who can easily discern that they add much more to the bulk of Books than of Knowledge. But this notwithstanding, Pyrophilus, I thought my self obliged on some occasions, for your sake, to overcome my Natural Averseness to stuff any Writings of mine with Passages transcribed from those of others, partly for the Reasons elsewhere insisted on, and partly for many others. As First, because some Particulars are of that Strangeness, and of that Moment, that they need and deserve to be verified by more than a single Attestation. Next, because according to the Greek Proverb[^3] --- it is not proper to say over the same thing again --- when the Observation, Experiment, or other Passage of an Author, is either illustrated or otherwise improved by the Repetition, or else applied to some purpose differing from that to which the Author brought it: That being applicable to many a single Experiment or Observation which Seneca[^4] somewhere says,*Nulla Res consummata est dum incipit; And, Etiamsi omnia à Veteribus inventa sunt, hoc semper novum erit, Vsus, et Inventorum ab aliis Scientia et Dispositio.* And thirdly, because as the Planets and other Stars have (according to Astrologers) in their great Synods or Conjunctions, much more powerful, and sometimes other Influences on the Air and some other sublunary Parts of the World, than are ascribed to one or two of them out of that Aspect; so many Particulars, which whilst they lay single and scattered among the Writings of several Authors were inconsiderable, when they come to be laid together in order to the same Design, may oftentimes prove highly useful to Physiology in their Conjunction, wherein one of them may serve to prove one part or circumstance of an important Truth, and another to explicate another, and so all of them may conspire together to verify that Saying, *Et quae non prosunt singula, multa juvant*. It may then I hope suffice to justify me on this occasion, that not appealing to other Writers as to Judges, but as to Witnesses, nor employing what I have found already published by them barely as Ornaments to imbellish my Writings, and much less as Oracles by their Authority to demonstrate my Opinions, but as Certificates to attest Matters of fact, I may hope that their Testimonies will as well be illustrated by mine, as mine by their's, and that all of them may contribute to your better Information.

[^3]: In the spirit of the saying, I have removed original Greek.

[^4]: [original footnote] Quaestion. Natural. lib 6. cap 5. Epistola 64.

And if, Pyrophilus, you grant that upon these Considerations I have not done amiss to apply to my purpose many of those things which I found delivered pertinently to them by those Writers which I chanced to cast mine Eyes on, I suppose you will not think I need to make you an Apology for my having made most use of the Passages of those Writers which I suppose will be most difficult to be met with (such as are many Books of Navigations and other Voyages) and especially of French Books not yet translated into English or Latin. And I think I shall less need to make an Excuse for my having for the most part set down the Passages I recited in the Authors own Words, that being one of the readiest ways I know to satisfie the Reader, and avoid injuring the Writer. And indeed, I have met with abundance of Quotations wherein the Transcriber doth so mistake, or so mis-represent the cited Authors Meaning, sometimes out of Inadvertence, but sometimes too I fear out of Indulgence to his own Hypothesis, that if ever I should be tempted to trouble the World with any of my thoughts, I would beseech my Readers, not to look upon any thing as my Opinion or Assertion that is not delivered in the entire Series of my own Words; lest a Transcriber should make me deliver those things resolutely and dogmatically, which I deliver but hesitantly and conjecturally; and lest I should seem to set down those things Positively as Processes for whose success I undertake, which I record but by way of Narrative.

For my so frequently mentioning what I have borrowed from other Writers, or received from my friends, I expect to be excused by that of Pliny, *Benignum est (ut arbitror) et plenum ingenui Pudoris, confiteri per quos profeceris.* Though I have seen many Modern Writers that so boldly usurp the Observations and Experiments of others, that I might justly apply to them what the same Pliny annexes; *Scito enim, conferentem Authores me deprehendisse à juratissimis et proximis Veteres transcriptos ad Verbum, neque nominatos etc.* If other Writers should not prove more equitable (for I will not say more thankful) than such as these, they would quickly discourage those whose aims are not very noble and sincere, from gratifying the Publick with Inventions, whose Praise and Thanks would be usurped by such as will not name them. But perhaps they would be more just if they reflected on what our Author further adds, *Obnoxii profectò animi et infelicis ingenii est, deprehendi in furto malle quam mutuum reddere, cum praesertim sors fiet ex Vsura.*

And now I have said this concerning the Passages I have borrowed from other Authors, it will not be improper to add something about those I have declined to borrow. For you may possibly marvel, that in many of the Historical parts of my Writings I have omitted such Testimonies either of Pliny, Solinus, Aristotle, Theophrastus, Aelian, or perchance some of the ancient Physicians themselves (who yet, as more conversant with things, are usually more credible) as seems very pertinent to my Discourse, and fit to prove what I design. But when I shall come to entertain you about Natural History, I doubt not but to satisfie you with the Reasons I shall offer you of this Practice. In the mean time, I shall only tell you in short, that though I have a just respect for those Great Names I have mentioned; yet the sense I have of the difficulties I have found to make and relate an Observation accurately and faithfully enough for a Naturalist to rely on; and the occasions I have had of looking into many matters of fact delivered in their Writings, with a bold and an impartial Curiosity; have made me conclude so many of those Traditions to be either certainly false, or not certainly true, that except what they deliver upon their own particular Knowledge, or with peculiar Circumstances that may recommend them to my belief, I am very shy of building any thing of moment upon foundations that I esteem so unsure, and much less upon the suspected Passages that Wecker, Paracelsus, Porta, etc. abound with. And therefore (though I well enough know how much I impoverish my Discourse by this Niceness) yet I do not think it fair to imploy that as an Argument to convince you that has not that operation upon me my self. And I the rather take notice of my forbearing to make use of the Historical Traditions and Chemical or Magical Secrets that I meet in the above-mentioned Authors, or any other makers of Collections, unless the Narrative be (as I was saying) expresly enough delivered upon the Writer's Personal Knowledge, or that of some other credible Witness; not only because I would give you an account why several of my Writings are unfurnished with what most Readers look on as the richest Ornaments of other mens, but because if this wariness could be introduced, t'would be the most effectual way of perswading men to write those kind of Tracts I would recommend, Physiological Essays. For he that will confine himself so strictly, will scarce be often tempted on Physical Subjects, to write either Systems or Volumns.

Another things, Pyrophilus, I must needs advertise you of in reference to the ensuing Discourses, which is, That besides those Deficiencies in point of Ratiocination which are due to my personal Disabilities, I have purposely let pass some Few (and but very Few) Inferences which I discerned well enough not to be cogent, because I was willing to acquaint you upon some particular Occasions with all the Experiments then occurring to me, which I thought might contribute to the Illustration of the Subject in hand, though each of them apart did not irrefragably, nor indeed so much as strongly infer the Conclusion in order to which they seemed to have been mentioned as Premisses. And this Practice I made the less scruple of, because I was willing to exercise thereby your Reasoning Faculty, and try how far you would discern the Tendency of several things, all of them pertinent enough to the Subject in hand, but not all of them concluding to the main design in order whereunto they were alledged. And I supposed that the things by me mentioned, though not conclusive, being yet Experimental, the mention of them, which in a strictly Logical way of reasoning must have been forborn, might well make you amends for the Exercise to which I intended they should put your Reason.

There remains yet one thing, Pyrophilus, of which I suppose you will expect I should give you an Account; and that is, why in the ensuing Essays I have mentioned many Experiments which I have not plainly and circumstantially enough delivered. To satisfie you concerning which, I must represent to you, First, That though for your sake I have oftentimes, contrary to my Reason and Genius, delivered things, to make them more clear, in such a Multitude of words, that I now seem even to my self to have in many places been guilty of Verbosity; yet in some other passages, treating of things which Use had rendered very familiar to me, I may have, to shun Prolixity, unawares slipt into the Contrary Extream. Secondly, There are some Mechanical Experiments wherein I have purposely omitted some manual Circumstances, because I was unwilling to prejudice some ingenious Trades-men, who make either a Livelyhood, or at least a gain, by the sale of the productions of such Experiments. And I made the less scruple to conceal such Mechanical Circumstances, (if I may so call them) because they were not necessary to the Physiological Knowledge of the Experiments: in naming of which my intention was to teach you rather Philosophy than Trades. Thirdly, I mentioned some things but darkly, either because I received them upon Condition of secrecy, or because some ingenious persons that communicated them to me, or others to whom I imparted them, do yet make, and need to make, a pecuniary advantage of them. Fourthly, And some things that, either having been the fruits of my own Labours, or obtained in Exchange of such, are freely at my own disposal, I have not yet thought fit so plainly to reveal, not out of an envious design of having them buried with me, but that I may be always provided with some Rarity to barter with those Secretists that will not part with one Secret but in Exchange for another, and think nothing worth their desiring that is known already to above one or two Persons. And I think it very lawful to reserve always some concealed Experiments by me, wherewith to obtain the secrets of others, which being thereby gained, the other (as being no longer necessary to the former end) may freely be communicated.

And think not, Pyrophilus, that the bare mention of an Experiment as having been performed, though the way of making it be concealed, is of no use, if the Relator of the Experiment be a Person that may safely be credited: For it is something to be assured that such and such things have been really performed, and consequently are possible to be done, though we be not yet particularly acquainted with the means of performing them. And he tells you something, that tells you upon his own Knowledge, that in such or such Bodies, or Ways of operating on them, considerable things of such or such a Nature are to be met with. And for my part, when I go a Hawking or Setting, I think my self beholden to him that assures me that in such a field there is a Covey of Partridges, though he does no more towards the giving me them. And it is obvious how much Europe is beholden to Columbus for the Detection of many Countries in America which were not discovered by him, nor perhaps till long after his Death, because he first informed us Knowingly that there were unknown Regions beyond that vast Ocean which severs the Old World from the New. But I begin to digress, and therefore shall proceed to tell you, That I am the less troubled at my Omission of the circumstantial parts of some Experiments, because I think it will be much for your Advantage to try them over again your self. And as I have taken care by the truth of the Experiments I have delivered to secure your success, in case you try them aright; so I cannot be very sorry that you should in some Particulars have a kind of Necessity laid on you to exercise your own industry, and thereby encrease your Experience.

But besides all that has been said, Pyrophilus, I must freely confess to you, that there is one thing particularly relating to your self, which has made me refrain from delivering in the ensuing Essays some of the chief Chemical processes wherewith they might have been enriched. For not yet knowing with what seriousness you will addict your self to promote experimental Philosophy, nor what use you will make of what has been unveiledly communicated to you, I was somewhat unwilling that some things which had cost me a great deal of pains should yet fall into any man's hands that scorns to purchase Knowledge with some pains, and I was desirous, in case you shall prove as industrious as I hope you will, to have something by me to encourage and cherish your industry, which may be more suitable to your improved Knowledge. For I must confess to you, that in reference to the Chemical processes extant in the following Discourses, I look upon most of them but as trifles, not only in comparison of those things which a knowing Chemist might have delivered on the same subjects, but even in regard of many processes (not impertinent to those discourses) wherewith I my self, (as little as I am a Pretender in these Matters) am not unacquainted: and perhaps I would have given to the following Treatises the Title of Trifles, instead of that of Essays, if I had not been afraid of discouraging you thereby, and if the Chemical part of them had been the chief thing wherewith I intended to acquaint you in them. But if the reception you give to what we have already written, prove such as may encourage us to proceed, we may perhaps, if God be pleased to vouchsafe us Life and Opportunity, be invited to impart to you those more considerable Chemical Experiments, which either the Communication of our friends or our own Labours have presented us. For it will be much in the power of the Entertainment which these Papers shall meet with, to make them either the Beginning of our Labours of this nature, or the End. And in the meantime, I think I may venture to tell you, that, as inconsiderable as I have confessed many of the Chemical Processes mentioned in these Essays to be, yet if ever you take the pains (as I hope you will) to Experimental Essays, and confine your self to take as little upon trust as I have done, you will perhaps be ready to believe, that sometimes a short Essay of this nature, not to say some one single Experiment, may have cost me more than a whole Treatise written on such a Subject, whereon to be able without Discredit to write Books, it is almost sufficient to have read many. And give me leave to add, that as in such kind of Composures, oftentimes the enabling himself to give a considerable Advertisement, or even Hint, may cost the Writer more than the making of several Experiments; so it may be also more beneficial to the Reader than the Knowledge of them. For we must not always measure the Considerableness of things by their most obvious and immediate usefulness, but by their fitness to make or contribute to the discovery of things highly useful. As, if it be true, what is reported by good Authors of the hazel Wand, or Virgula divinatoria, though the hazel Tree be much less considerable in reference to its fruit, or immediate productions, than a Peach-Tree, an Orange-Tree, or even an Apple-Tree; yet may it be made much more valuable than any of them, because whereas they only present us with fruits, this may assist us to discover in latent Mines inestimable Treasures.

I had almost forgot to advertise you, Pyrophilus, That whereas I have not been so sollicitous as most Writers are wont to be, to swell the ensuing Essays with the Enumeration of the various Opinions and Arguments of Authors about the Subjects I treat of, or to adorn them with acute Sentences, fine Expressions, or other Embellishments borrowed from eminent Writers; it has not been, because I utterly dislike the making use of those passages in Classick or other Authors, that may either give (among the Admirers of those Writers) some Authority to our thoughts, or very handsomely and Emphatically express them. For I remember, I have known it reprehended by Learned Men in Epicurus, That though he writ very much himself he would not vouchsafe in his Writings to quote those of other Men. And that I have not refrained from making use, now and then, of those Philological Ornaments of Discourse, when they readily occured to me, and appeared neither impertinent nor prolix, may I hope suffice to keep me from being suspected of the Vanity of thinking my self above other mens assistance. But the reasons of my so much declining to make use of other mens Authority, or Expressions, were chiefly these. First, That the Weakness of my Eyes has this long time kept me from reading almost any Books, save the Scripture, with some Critical Expositions of it, and here and there some Portions of the Writings of those that pretend to teach their Readers Experimental Matters: And the unfaithfulness of my Memory as to things of no great Moment, has made me forget almost all the little Philological and florid Learning I was formerly acquainted with. And really, Pyrophilus, as for the Books that treat of Natural Philosophy, I am so sensible of the smalness of the Advantage which my Disabilities have suffered me to make of them, that instead of being ambitious to appear a great Reader, I could be very well content to be thought to have scarce looked upon any other Book than that of Nature. And in the next place, Pyrophilus, though I ignore not that by this plain and unadorned way of Writing, I unkindly deny my Essays many Embellishments which I might give them, and which perhaps you will think they do abundantly need; yet my frequent Distempers, Journeys, and other Avocations, not allowing me so much time as I desired, to entertain you on Philosophical subjects, I thought it more requisite to spend those confined hours in acquainting you with my own thoughts, such as they are, than with those of other Men; unless (as I formerly intimated) I can some way or other more than barely recite what I recite of theirs. And you will easily pardon me the injury which for your sake I do my own Reputation by this naked way of writing, if you, as well as I, think those the profitablest Writers, or at least the kindest to their Perusers, who take not so much Care to appear Knowing Men themselves, as to make their Readers such.


