---
title: "The Unsuccessfulness of Experiments (II)"
author: "Robert Boyle (1627-1691)"
output: tint::tintPdf
latexfonts: 
  - package: lato
    options: default
  - package: FiraMono
linkcolor: "0.3,0.3,0.6"
---

```{r setup, include=FALSE}
library(tint)
# invalidate cache when the package version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tint'))
options(htmltools.dir.version = FALSE)
```



What has been already said, Pyrophilus, may, I hope, suffice to show you, how experiments may miscarry upon the account of the materials employed in trying them.  And therefore we shall now pass on to consider the contingencies, to which experiments are obnoxious, upon the account of circumstances, which are either constantly unobvious, or at least are scarce discernible till the trial be past.  And because these circumstances can hardly be discoursed of in an accurate method (which their nature will scarce admit of) I shall not tie myself to any other order in setting down the instances, which occur to me on this occasion, than that wherein they offer themselves to my memory.
       
And first I must acquaint you with what was not long since seriously related to me by Doctor K., a person exceeding far both from the custom, and, in this particular, from the temptation of telling untruths.  He then assured me, that lending his laboratory in Holland to a friend of his during his own absence, and leaving in that laboratory among other things great store of aqua fortis of several compositions, which he had made, to employ about his famous scarlet-dye, this friend of his sent him word a while after his departure, that by digesting gold with an aqua fortis, he had separated the tincture or yellow sulphur from it, and made it volatile (the remaining body growing white) and that with this golden tincture he had, not without gain, turned silver (as to part of it) into very perfect gold.  Upon which advertisement the doctor speedily returning to his laboratory, did himself with the same aqua fortis many times draw a volatile tincture of gold, which did turn silver into true gold: and (that I may add that upon the bye, to gratify your curiosity) when I demanded, whether or no the tincture was capable to transmute or graduate as much silver, as equalled in weight that gold, from whence the tincture was drawn, he assured me, that out of an ounce of gold he drew as much sulphur or tincture, as sufficed to turn an ounce and a half of silver into that noblest metal.  Which I am the more disposed to believe, partly because my trials permit me not to doubt of the separableness of a yellow substance or tincture from gold; and partly because I am tempted to think, that silver may have in it a sulphur (to speak in the chemists language) which maturation is capable to graduate into a golden one, by having been certified by the observations of men very experienced in metalline affairs (and perhaps too by my own) that sometimes by corrosive liquors (which Sir Francis Bacon also, if I mistake not, somewhere observes) and sometimes by the operation of common sulphur (especially well opened and associated with fit salts) silver has afforded some grains of very pure gold.  But our doctor found himself much mistaken in the hopes of growing rich by this experiment; for a while after endeavouring to make it again, his hopes were frustrated, which he ascribes to the aqua fortis, and therefore has attempted the same work afresh.  But since all his trials have been hitherto fruitless, it is not improbable, that the disappointment proceeded from some other more abstruse cause; for we find such adventures to have sometimes befallen artists irreparably.  And Glauber alone, if you will therein credit him, tells us of several ways, by which he made gold once, and could not do it again.  Upon which subject I must not omit those very illustrious testimonies and instances of this nature, that I find recorded by that ornament of his age and quality, the prince of Mirandola, in his treatise *de Auro Novi*[^1]: 

> *'qui mihi asseruerit seme!  se ex mobili argento, quod vivum dicitur, stabile verumque argentum confecisse succis et foliis herbarum, idque vendidisse peritis explorandae metallicae veritatis; eisdem mox usum se foliis frustra, et quod semel perfecerat, nunquam alias, quanquam id saepe tentaverit, perficere potuisse. Alium novi qui adhuc apud vivos moratur, cui cum aurum et argentum circiter quindecies per artem effectum esset, amisit artem eam, accepitque oraculo socii per quietem habito, id ingratae mentis vitio contigisse.  Ut hinc etiam veritatem apostolici dicti condiscamus, Neque qui plantat, neque qui rigat, est aliquid, sed incrementum dat Deus.'*

[^1]: [original footnote] Lib. 3. cap. 6.


And to both these narratives our learned prince does in the same book add many others.

> '*Retulist quidam mihi sese aurum ex argento fecisse semel magna copii; secundo se usum eisdem rebus, fecisse quidem, sed minimâ semper quantitate, sic ut detrimentum lucro majus esse supputaverit.  Venisse in mentem, uti detrimentum effugere possit, si non ex argento, sed ex aere melioris conditione metalli, sese consequi experiretur, idque se conjecturis firmis nixum tentavisse: cumque in eo fuisset, ut rem sese adepturum speraret, miris modis evenisse, ut nihil omnino consequeretur. Idemaffirmavit ab amico, qui expertus hoc ipsum suerat accepisse, qui cum ex cinnabari argentum fecisset optimum, saepenumero sese postea insistentem operi majore cum diligentia semper eventu rei fuisse frustratum.*'

And to these relations of this famous prince I could add others of some acquaintances of mine, who having either once or twice made luna fixa (as artists call that silver, which wanting but the tincture of gold abides the trial of aqua fortis, etc.) or some other profitable experiment, have since in vain attempted to do the like again; and yet have their eyes so dazzled by the gold and silver they have (either separated or) made, that they are not to be prevailed with to desist from prosecuting their uncertain hopes.
       
 That many experiments succeed, when tried in small quantities of matter, which hold not in the great, it may save you something to be advertised of; many projectors, especially chemists, having already very dearly bought the knowledge of that truth, for oftentimes a greater and unwieldly quantity of matter cannot be exposed in all its parts to a just degree of fire, or otherwise so well managed, as a less quantity of matter may be ordered.  But this is so manifest a truth to those, that have dealt much in experiments, that whereas many chemists would be vastly rich, if they could still do in great quantities what they have sometimes done in little ones, many have undone themselves by obstinately attempting to make even real experiments more gainful.

I have not been very solicitous to subjoin particulars to the foregoing observations, because that by reason of the contingency of such experiments, as would be the most for my present purpose, you might possibly be tempted to lose toil and charges upon trials, very likely not only to delude your hopes, but perhaps to make you distrust the fidelity of our relations.  Yet for illustration-sake of what we have delivered, I am willing to mention some few contingent experiments, that occur to my thoughts.

And first, it is delivered by the Lord Verulam himself, as I remember, and other naturalists, that if a rose-bush be carefully cut as soon as it has done bearing, it will again bear roses in the autumn.  Of this many have made unsuccessful trials, and thereupon report the affirmation to be false; and yet I am very apt to think, that the Lord Verulam was emboldened by experience to write as he did.  To clear up which difficulty, let me tell you, that having been particularly solicitous about the experiment, I find by the relation both of my own and other experienced gardeners, that this way of procuring autumnal roses will in most rose-bushes most commonly fail, but in some, that are good bearers, it will succeed; and accordingly having this summer made trial of it, I find, that of many bushes, that were cut in June in the same row, the greater number by far promise no autumnal roses, but one, that has manifested itself to be of a vigorous and prolific nature, is at this present indifferently well stored with damask-roses.  And there may be also a mistake in the kind of roses; for experienced gardeners inform me, that the musk-rose will, if it be a lusty plant, bear flowers in autumn without the help of cutting.  And therefore that may be mis-ascribed to art, which is the bare production of nature.  And cinnamon rose-bushes do so much better thrive by cutting than several other sorts, that I remember, this last spring, my gardener having (as he told me) about mid April (which was as soon as that kind of rose-bush had done bearing) cut many of them in my garden, I saw about the middle of June store of the same bushes plentifully adorned both with buds and with blown flowers.

An uncertainty not unlike that, which we have newly taken notice of in the experiment of producing autumnal roses, has been likewise observed in the attempts, that have been made to make many sorts of fruit grow upon the same tree.  And as for differing sorts of fruits of the same denomination, as apples, pears, etc. though some severe naturalists are unwilling to believe, that they can be made to grow upon the same tree; yet we dare not imitate their severity, having lately seen various sorts of pears fed by the same tree, and elsewhere three and twenty sorts of apple-grafts flourishing upon the same old plant, and most of them adorned with fruit.  Nay, and though the fruits be not of the same denomination, yet if they be of kin in nature, they may very possibly be brought to grow on the same tree: for we lately gathered ripe apricots and ripe plums upon one tree, from which we likewise expect some other sorts of stone-fruit.  But to make fruits of very differing natures be nourished prosperously by the same stock, is so difficult a thing, that we can at most but reckon it among contingent experiments.  For though Pliny and Baptista Porta relate their having seen each of them an example of the possibility of producing on one tree great variety of differing fruits; and though such a person as the deservedly-famous astronomer Dr. Ward assures me, that he has particularly taken notice of pears growing upon an apple-tree; and I elsewhere add a resembling observation of ours; yet certainly this experiment has been for the most part but very improsperously attempted; nor have I yet ever seen it succeed above once, though tried with very much care and industry.  And I remember, that this very year, in the same garden where I gathered the apricots and plums above mentioned, I saw the [buds] of a pear-tree so skilfully grafted upon an apple-stock, that it flourished very much with blossoms in the spring, and gave me great hopes, that it would bear fruit this newly-past summer, but has deceived my expectation; as many other plants so grafted in the same garden have for many years deluded the hopes of the skilful master of it, who assures me, that though many of them did for some years successively afford promising blossoms, yet they all decayed away without bearing any of them any fruit.  Which yet may seem somewhat strange, since not only we have this summer gathered pears upon a graft, which a divine, to whom the garden belongs, affirmed to have been grafted upon a quince-tree; and the industrious Kirchir tells us, that *Experientia docet Persicum moro insitum fructus proferre, etc. de quo nullum est dubium utpote vulgare pene:*[^2] 'but experience tells us, that as little as a white-thorn and a pear-tree seem of kin, a [bud] of the latter will sometimes prosper will, being grafted upon a stock of the former.'

[^2]: [original footnote] Artis Mag. Luis et Umbrae, lib. 1 p 3 cap. 6.

To contingent experiments, Pyrophilus, you may, if you please, refer what is delivered by those learned writers, who affirm, that if a lixivium made of the ashes or fixed salt of a burned plant be frozen, there will appear in the ice the idea of the same plant; for we have many times purposely made trial of this experiment without the promised success.  And I remember, that in the last cold season, proper for such trials, I purposely made a lixivium of fair water and salt of wormwood; and having frozen it with snow and salt after the manner of congelation elsewhere declared, I could not discern in the ice anything more like to wormwood than to several other plants.  And having about the same time, and after the same manner, exposed to congelation a thin phial full of a strong decoction of wormwood (from which an idea of the plant may be more probably expected) those, to whom I showed it, after it was frozen, could discern as little like wormwood in it as myself.  It is true, that in both these phials the ice seemed somewhat oddly figured; but it is true also, not only that we have observed that water, wherein a saline body, as salt petre, or sea-salt, or sugar, etc. has been dissolved, has afforded us ice, which seemed to shoot into several figures, but even in ordinary water congealed we have often seen ice figured, as if the water had been no elementary body; which needs not be admired since (to omit other causes, which may concur to the production of this effect) many waters gliding through earths abounding in saline particles of this or that nature, may be easily, in their passage, impregnated with them; whence perhaps it comes to pass, that dyers find some waters very fit, and others very unfit for the dying of scarlet and some other colours.  And therefore we cannot but think, that the figures, that are oftentimes to be met with in the frozen lixivium or decoction of a plant, will afford but uncertain proofs, that the idea of each, or so much as of any determinate plant, displays itself constantly in that frozen liquor.  And I much fear, that most of those, that tell us, that they have seen such plants in ice, have in that discovery made as well use of their imagination as of their eyes.  And it is strange to observe what things some men will fancy, rather than be thought to discern less than other men pretend to see.  As I remember Mr. R. the justly famous maker of dioptrical glasses, for merriment telling one, that came to look upon a great tube of his of thirty foot long, that he saw through it in a mill six miles off a great spider in the midst of her web; the credulous man, though at first he said he discerned no such thing, at length confessed he saw it very plainly, and wondered he had discovered her no sooner.  But yet, Pyrophilus, because two or three sober writers do seriously relate some stories of that nature upon their own observation, I am content for their sakes to reckon their experiments rather among the contingent than the absolutely false ones; for it is not impossible, but that among the many figures, which frozen liquors do sometimes put on, there may appear something so like this or that plant, that being looked upon with the favourable eye of a prepossessed beholder, it may seem to exhibit the picture of the calcined vegetable: and we ourselves, not very long since, setting to freeze in snow and salt a fine green solution of good verdegrease which contains much of the saline parts of the grapes coagulated upon the copper by them corroded) obtained an ice of the same colour, wherein appeared many little figures, which were indeed so like to vines, that we were somewhat surprised at the experiment; and that which increased our wonder was, that another part of the same solution being frozen in another phial by the bare cold of the air, afforded us an ice angularly figured as we have observed the ice of saline liquors oftentimes to be) but not at all like that made by the application of snow and salt.  And having, for further trial sake, suffered that ice, wherein the vines appeared to thaw of itself, and having then frozen the liquor a second time in the same phial, and after the same manner as formerly, we could not discern, in the second ice, anything like that, which we had admired in the first.  And in wine and vinegar, as much as those liquors partake of the nature of the vine, we have not, after congelation, observed any peculiar resemblance of it in figure.

The mention we have been making of ice brings into my memory another experiment, which may perhaps be reckoned likewise among contingent ones, and that is the experiment of burning with ice as with a glass lens; which though some eminent modern writers prescribe to be done, without taking notice of any difficulty in it, yet both we and others, that have industriously enough tried it, have met with such defeating circumstances in it, especially from the uniform texture wont to be met with in most ice, that the making of such burning glasses may be well enough referred to those experiments, whose constant success is not to be relied on, as we elsewhere more particularly declare.

In the trade of dying there is scarce any tinging ingredient, that is of so great and general use amongst us a woad or glastum; for though of itself it dye but a blue, yet it is used to prepare the cloth for green and many other of the sadder colours, when the dyers have a mind to make them permanent, and last without fading; but yet in the decocting of woad to make it yield or strike its colour, there are some critical times and other circumstances to be observed; the easy mistake of which oftentimes defeats the dyer's expectation to his very great loss, which sometimes he knows not to what to impute, of which I have heard several of them complain: and therefore many of our less-expert dyers, to avoid those hazards, leave off the use of woad, though growing plentifully enough here in England, and instead of it employ indico, though it cost them dearer, as being brought hither sometimes from Spain,  sometimes from the Barbadoes, and oftentime even from the East-Indies.

Our London refiners, when, to part silver and copper, they dissolve those mixed metals in aqua fortis, are wont afterwards to dilute the glutted menstruum with store of fair water, and then with copper-plates to strike down the dissolved silver.  But because by this manner of proceeding much copper is wont, after the separation of the silver, to remain in the menstruum, as may appear by its high tincture, that this thus impregnated liquor may be improved to the best advantage, they are wont to pour it upon what they call whiting which is said to be a white chalk or clay finely powdered, cleansed, and made up into balls) wherewith the tincted parts incorporating themselves, will, in some hours, constitute one sort of verditer fit for the use of painters, and such other artificers as deal in colours, leaving the remaining part of the menstruum an indifferently-clear liquor; whence they afterward, by boiling, reduce a kind of salt-petre fit, with the addition of vitriol (and some fresh nitre) to yield them a new aqua fortis.

And these things I mention, Pyrophilus, that you may know what I mean, when I tell you, that sometimes the refiners cannot make this verditer for a great while together, and yet cannot tell, whence their disability to make it proceeds.  Of which contingency I remember I lately heard one of the eminentest and richest of them sadly complain, affirming, that neither he, nor many others of his profession, were able, not long since, to make verditer for many months together; and that several others were yet at a loss in reference to that particular: though for his part he had, without knowing the cause of this contingency, found a remedy for it, namely, to warm the menstruum well before it be poured on the whiting; on which, when the liquor was warm, the tincted parts would fasten, though they would not, whilst (according to the custom of refiners) it was poured on cold.
       
Making likewise the other day a visit to the chief copperas work we have in England, one of the overseers of it, who went along with me to show me the contrivance of it, assured me, that many times, by the mistake or neglect of a circumstance in point of time, they had lost, and are yet subject to lose, some thousands of pounds of vitriol at a time, which in spite of their wonted, but not sufficiently attentive and skilful care, would degenerate into an unctuous substance, not to be reduced into good vitriol again; unless by the tedious way of throwing it abroad, and exposing it with the unprepared stones, from which they draw their vitriol, to the rain and sun to be opened anew, and fitted for the yielding of vitriol after the same manner with those crude minerals.

Upon this occasion I must not omit, because much conducing to the scope of our present discourse, a memorable relation, that I have met with in the Indian History of the learned Josephus Acosta, who diligently surveyed the famous and almost inestimable mines of Peru, and (for one that was not a chymist) has delivered many considerable and judicious observations about them.  That which I am now to mention, is in that chapter, where he treats of the silver of the Indies, set down in these words: 

> 'It is strange to see not only the difference between the refining of metal by fire, and without it by quick-silver, but also that some of these metals which are refined by the fire, cannot well be molten with any artificial wind, as with bellows, but when it is kindled, and blown with the natural air or natural wind.  The metal of the mines of Porco is easily refined with bellows; and that of the mines of Potosi cannot be molten with bellows, but only by the breath of their guayars, which are small furnaces upon the sides of the mountains, built expressly where the wind lies, within the which they melt this metal: and though it be hard to yield a reason of this difference, yet it is most certain and approved by long experience.'[^3]

[^3]: [original footnote] Josephus Acosta, [?] 4. cap. 5.

If there be any trade that obliges the artificers to be assiduously conversant with the materials they employ, it is that of the glass men; and yet even to them, and in their most ordinary operations, there happen now and then little accidents, which, though they know not well to what to ascribe, are not yet capable of hindering them from doing sometimes what they have done a thousand times.  And I remember, that among the last times I have been at a glass-house, an eminently-skilful workman, whom I had purposely engaged to make some vessels for me, that required more than ordinary dexterity, was not able, when I came thither, to make metal (as they call that colliquated mixture of sand and fixt salt, whereof they blow their glasses) tolerably fit to be employed: wherefore he desired me to take the pains to come again another day, and he would try to repair his unluckiness.  But the next time I came, though it were upon appointment, his metal proved again unserviceable, and instead of being colourless, when it was cold, looked as if it had been stained with blue and yellow, and was besides brittler than it ought to have been.  So that it need be no such wonder, if philosophers and chymists do sometimes miss of the expected event of an experiment but once, or at least but seldom tried, since we see tradesmen themselves cannot do always, what, if they were not able to do ordinarily, they could not earn their bread.

It is affirmed by Helmont and others, that treat of the Lapides Cancrorum, that they grow within the skulls of those craw-fishes, from whence they have their name: but I have known good anatomists complain, that they have sought them in vain in the heads of those fishes, which may well make them distrust the veracity of those, that ascribe them to that sort of animals; yet we have often taken those stony concretions out of the heads of craw-fishes.  But passing lately through Hungerford, a town famous for the plenty of such kind of fish, we made diligent enquiry concerning their nature, and were there informed by those that looked to them, that the concretions above-mentioned are to be found in their heads but about that season of the year, wherein they shift their shells, and that at other times of the year, several persons had in vain endeavoured to store themselves with crabs eyes at Hungerford.  And indeed, having at the last time of my being there (which was about the latter end of June) caused many large ones to be taken out of the water, we found these little stones but in the head of one of them; whereas about a fortnight before, which was near the summer solstice, passing by that place, we found in the wonted parts of the heads several such concretions, as to bigness and shape, but so soft, that we could easily crush and discind them between our fingers.  And certainly the mistake of the circumstance of time has much prejudiced the reputation of many truths: and I remember, that Asellius, to whose anatomical fortune the world is so much beholden, ingenuously acknowledges, that he had like to have lost the discovery of the milky veins, because having at first suspected those unlooked-for white vessels, which he took notice of in the mesentery of a dog dissected alive, to be some irregular ramification of nerves, he was much confirmed in his conjecture by the next dog he opened; for having dissected him at an inconvenient distance of time from the dog's repast, the slender vessels he looked for being destitute of the chyle, which is it, that makes them conspicuous, did not appear.  So that he had lost the benefit of his first lucky observation, had not his sagacity inclined him to suspect, that if a dog was plentifully fed at a convenient distance of time before his being dissected, the vessel swelled with alimental juices would be the better discernible: whereupon, having feasted another dog some hours before he opened him, he manifestly detected those milky vessels, whose discovery has since set anatomists so usefully on work.

But, Pyrophilus, not to exceed the limits of an essay, I must not multiply instances of the contingencies of experiments, but content myself to tell you in general, that in many cases such circumstances as are very difficult to be observed, or seem to be of no concernment to an experiment, may yet have a great influence on the event of it.  If on either of the extremes or poles of a good armed load-stone, you leisurely enough, or many times, draw the back of a knife, which has not before received any magick influence, you may observe, that if the point of the blade have in this affrriction been drawn from the middle of the equator of the load-stone towards the pole of it, it will attract one of the extremes of an equilibrated magnetick needle; but if you take another knife, that has not been invigorated, and upon the self-same extremity or pole of the load-stone thrust the back of the knife from the pole towards the equator, or the middle of the load-stone, you shall find, that the point of the knife has, by this bare difference of position in the blade, whilst it past upon the extreme of the load-stone, acquired so different a magnetick property, or polarity, from that, which was given to the former knife by the same pole of the load-stone, that it will not attract, but rather seem to repel or drive away that end of the magnetick needle, which was drawn by the point of the other knife.  And this improbable experiment not only we have made trial of, by passing slender irons upon the extremities of armed load-stones, the breadth of whose steel caps may make the experiment somewhat less strange; but we have likewise tried it by affrictions of such irons upon the pole of a naked terella, and we found it to succeed there likewise: how strange soever it may seem, that the same point or part of the load-stone should imbue iron with contrary properties, barely as they are, during their passing over it, drawn from the equator of  the load-stone, or thrust towards it.  But whether, or how far this observation insinuates the operation of the load-stone to be chiefly performed by streams of small particles, which perpetually issuing out of one of its poles, do wheel about and re-enter at the other; we shall not now examine, (though this seem one of the most likely phenomena we have met with, to hint a probable magnetic hypothesis) contenting ourselves to have manifested, by what plainly appears, how much influence a circumstance, which none but a magnetic philosopher would take notice of, may have on an experiment.  We have also, with pleasure, observed, how artificers in the tempering of steel, by holding it but a minute or two longer or lesser in the flame (or other competent heat) do give it very differing tempers, as to brittleness or toughness, hardness or softness: for as when it is taken out of the flame to be extinguished, it looks either red, yellow or blue; so they esteem and find it fit to make knives, engraving tools, or springs for watches, etc. and yet it passes from one colour to another so swiftly, that none but an artist expert in tempering of iron would suspect, that so small a difference of time of its stay in the flame could produce so great a difference in its tempers.  On which occasion, Pyrophilus, I call to mind, that making a while since some trials concerning gravers in the shop of a famous artificer, he presented me, as a great rarity, a graver (which I yet keep) that would make the usual experiments about tempering of gravers appear false to him, that should never try them but upon it; for with all the care, wherewith I tried upon it the known ways of softening gravers, I could not soften this: which men eminently skilled in these matters (together with the person that made it) affirmed to have been made of Damasco-steel, the strength whereof in cutting iron I have (not without some wonder) made trial of.  But whether this singularity, which we have mentioned in this graver, proceeded from the nature of the steel, or from the temper, that it had afterward given it, is not yet agreed upon by those skilful men, to whom I have showed it: but one of them, who by making instruments for navigators, has had the opportunity of making more than ordinary inquiry into matters of this nature, assures me, that he can easily soften this kind of steel, by only taking it off the fire at a certain nick of time, differing from that, which is wont to be observed in order to the softening of common gravers.  And who knows, but that in many other experiments, seemingly despicable and unheeded circumstances may be of great concernment, though by reason of want of such particular observations, as the frequent dealing with the same body has given magnetic philosophers and artificers occasion to make, men have not yet taken notice of their importance?

To give you one instance to this purpose, Pyrophilus, let me take notice to you, that many planters of fruit-trees have with wonder observed, that some grafts of cherry-trees, for example, have borne fruit the same year that they were grafted, (nay, I have observed some plants to bear fruit the same quarter of the year) and others not till the year after their insition, though neither in the goodness of the graft, nor in that of the stock, they had observed any disparity, to which the difference abovementioned could be ascribed; and therefore the bearing or not bearing of the [buds] of a cherry-tree the first year of its insition is by many gardeners looked upon as a thing merely contingent.  And yet indeed it scarce deserves to be reckoned among such contingent experiments, as we have been hitherto treating of; for I am informed by the trials of more than one of the most skilful and experienced grafters of these parts, that a man shall seldom fail of having cherries borne by his graft the same year, in which the insition is made, if he take care, that his graft, which must be of a good kind, have blossom-buds, as they are wont to be called, upon it: whereas if it were only leaf-buds, as they may be termed, it will not bear fruit till the second season.  And this not being taken notice of by vulgar gardeners, makes them, as we have said, impute a needless contingency to the fruitfulness of such kind of grafts.  Now to discern such buds as are fit to produce blossoms, from such as will display themselves but in leaves, is no difficult matter, the former sort being more full, and big, and round than the latter, which are wont also to lie more flat and close to the graft.  And it was, Pyrophilus, such observations as this, that induced us, after the beginning of the former essays, to discriminate from such contingent experiments as those, wherein the cause of the contingency is very abstruse and difficult to be discerned, such other experiments, whose seeming contingency proceeds from more easily discoverable causes; for such, by diligent observation of circumstances, may be reduced to a greater certainty than the others seem capable of.  Though I dare not deny, that even many of those contingent experiments, which to us yet seem to belong to the first sort, by men's future skill and diligence in observation, may be made fit to be reduced to the second sort.
       
Before I leave this subject, Pyrophilus, I dare not omit to say something to you of the Virgula Divina, or rather Divinatoria, by which many mineralists pretend to discover the latent veins of metals.  Some use a forked hazel, whose horns they hold by the ends one in each hand; and others content themselves to chuse a hazel rod (which some will have to be all of the same year's shoot) and this they bind on to another streight stick of any other wood, and walking softly with it over those places, where they suspect the bowels of the earth to be enriched with metals, they say, that if they pass over a metaline vein, the want will, by bowing towards, discover it.  And some dealers in metals I know, who affirm, that by holding the metals successively in that hand, wherein a man holds the rod, he may discover what determinate metal is predominant in the vein: for when he puts into his hand that metal, wherewith the mine chiefly abounds, the wand will manifestly bow more strongly, that when it is held in the hand with any other metal.  What to determine concerning the truth of this perplexing experiment, I confess I know not.  For Agricola himself, after a long debate concerning it, gives us this account of his sense:

> '*Metallicus igitur quia eum virum bonum et gravem esse volumus, virgulâ incantatâ non utetur, quia rerum naturae peritum et prudentem, furcatam sibi usui non esse, sed, ut supra dixi, habe: naturalia venarum signa, quae observat.*'[^4] 

The diligent Kircherus informs us in his Arte Magneticâ, that having exactly tried the experiment with metals, (for he mentions not his having tried it with mines) he could not find it in any measure succeed; and we ourselves having several times made trial of it in the presence of the confidentest assertors of the truth of it, could not satisfy ourselves, that the wand did really stand either to the metals, when placed under it, or to the metalline veins, when we carried it over mines, whence metalline ore was at that very time digging out.  But on the other side, many good authors, and even our diligent country-man Gabriel Plat, though wont to be somewhat too severe to chemists, does ascribe very much to this detecting wand; and many persons, in other things very far from credulous, have as eye witnesses with great asseverations asserted the truth of the experiment before us: and one gentleman, who lives near the lead-mines in Somersetshire, leading me over those parts of the mines, where we knew that metalline veins did run, made me take notice of the stooping of the wand, when he passed over a vein of ore, and protested, that the motion of his hand did not at all contribute to the inclination of the rod, but that sometimes, when he held it very fast, it would bend so strongly as to break in his hand.  And to convince me, that he believed himself, he did, upon the promises made him by his stooping wand, put himself to the great charge of digging in untried places for mines, (but with what success he has not yet informed me.)  Among the miners themselves I found some made use of this wand, and others laughed at it.  And this I must take notice of, as peculiar to this experiment, that the most knowing patrons of it confess, that in some men's hands it will not at all succeed, some hidden property in him that uses the wand being able, as they say, to overpower and hinder its inclinatory virtue.  To which I must add what a very famous chemist, who affirms himself to have tried many other things with it besides those that are commonly known, very solemnly professed to me upon his own knowledge; namely, that in the hands of those very persons, in whose hands the rod will (as they speak) work, there are certain unlucky hours, governed by such planets and constellations, (which I confess I believed not enough to remember their names) during which it will not work, even in those hands, wherein at other times it manifestly will.  But of this experiment I must content myself to say, what I am wont to do, when my opinion is asked of those things, which I dare not peremptorily reject, and yet am not convinced of; namely, that they that have seen them can much more reasonably believe them, than they that have not.

[^4]: [original footnote] De re metellica, lib. 30. p. 28. Lib. 3. part 4. cap. 3.

Nor is it only in experiments, Pyrophilus, but in observations also, that much of contingency may be: witness the great variety in the number, magnitude, position, figure, etc. of the parts taken notice of by anatomical writers in their dissections of that one subject the human body, about which many errors would have been delivered by anatomists, if the frequency of dissections had not enabled them to discern between those things, that are generally and uniformly found in dissected bodies, and those which are but rarely, and (if I may so speak) through some wantonness, or other deviation of nature, to be met with.  I remember, that a while since being present at the dissection of a lusty young thief, we had opportunity to observe, among other things, that the interval between two of his ribs was near the back-bone filled up with a thick bony substance, which seemed to be but an expansion of the ribs, and appeared not to have grown there upon occasion of any fracture, or other mischance.  About the same time being at a private dissection of a large and young human body with some learned men, an ingenious person, professor of anatomy, there present, chancing to cut a great nerve, spied in the substance of it little of a very red liquor, which he immediately showed me, as wondering what it might be: but I concluding it to be blood, presently suspected that it might have proceeded from some small unheeded drop of blood wiped off by the brushy substance of the nerve from the knife wherewith it was cut.  Wherefore carefully wiping a dissecting knife, I did in another place cut the nerve asunder, and found another very little drop of pure blood in the substance of it as before.  This I did again elsewhere with like success, showing it to the by-standers, who admired to see a vessel carrying blood (for such they concluded it to be) in the body of a nerve, in regard they remembered not to have ever met with such an accident; though I the less admire it, because I have in an ox's eye or two observed in that coat, which the moderns commonly call the retina, and which seems to be but an expansion of the pith of the optick nerve, little turgent veins manifestly full of blood.

We further observed in that lately mentioned body, in which we took notice of the irregular conjunction of two ribs, that the lungs, which were very sound, had a supernumerary lobe on one side, which did so little differ from its companions, that we did not, till we had displayed the lungs, take notice of it.  And I remember, that a while before, being invited by a company of physicians to a private dissection, and the lungs, which otherwise seemed not unsound, appearing in many places fastened to the ribs, two ingenious anatomists, that were there present, did so little agree in their observations concerning such cases, that the one affirmed, that he had never seen any lungs (which had not been excessively morbid) tied to the thorax; and the other protested, that he had scarce ever opened a diseased body, wherein the lungs did not so adhere.  But if it were not improper to mind a young gentleman of venereal observations, I could easily give you an eminent proof of the disagreement of anatomical observators, by insisting on the controversy between the famous writers on that subject, concerning the anatomical notes or tokens of virginity; many eminent authors affirming, that they have seldom failed of finding them in one amongst very many dissected maids; and many other artists, both conspicuous and experienced, preremptorily professing, that they have seldom or never met with the pretended marks in persons even of the most undoubted virginity.  And certainly it is very strange, that about a matter, which seems so easily determinable by sense, accurate and sober men should so widely disagree; as that the one should profess he has very rarely, if ever, met with in a human body, what another affirms himself to have as seldom, if ever, missed.  But because, Pyrophilus, this subject is, perhaps, somewhat improper to be insisted on either to, or by, a young man, I shall pass on to tell you, that amongst the most accurate of our modern writers, I suppose you will readily allow me to reckon Dr. Harvey and Dr. Highmore; and that though in their excellent treatises of generation they both insist on the production and changes observable in hens eggs, as the patterns, whereunto the generation of other animals may be referred; yet have we many times, in the progress of nature in her formation of a chick, observed considerable variations in point of time and other circumstances (though in the main our observations commonly agreed) from what is by them delivered: which diversity may easily proceed from the different constitution of hens, their differing assiduity in sitting on their eggs, the differing qualifications of the eggs themselves, and several other particulars of the like nature.  And I remember, that the other day taking notice of this to my learned friend Dr. Highmore, he readily acknowledged to me, that he himself had likewise observed many circumstances in eggs whilst they were hatching, which varied from those set down by him in his book; though he had there accurately expressed the changes he discerned in those eggs, which at the same time afforded him his observations.  And indeed there are certain things of such a nature, that scarce any single man's accurateness in making a single observation about them can secure him from appearing unskilful or unfaithful in his observations, unless those, that shall afterwards examine, them, chance to be endowed with a somewhat more than ordinary either equity, or sagacity, or both.  For instance, he that first affirmed, that a needle animated by a loadstone did constantly convert its extremes to the opposite poles of the earth, could scarce suspect himself of having delivered anything, which he had not carefully tried.  And yet of those pilots, Gonzales Oviedo and Sebastian Cabot, (who are said to have in America first taken notice of the declination of the mariner's needle) he that did first in those far distant parts of the world compare the meridian line afforded by magnetical needles with one mathematically drawn, (which may be readily found by accurate sun dials) and thereby observe the variation of the needle, or its declination from the true meridian line, might easily conclude the observer formerly mentioned to have been faulty, by reason of his finding the needle's variation differing (perhaps by many degrees) from that delivered by the first observer.  And this second man's observation might appear to have been as carelessly made to a hundred other observers, if the observations of navigators had not made it apparent, that the declination of the needle is far from being the same in all places: for though Cardan[^5] (as Kircher and Fracastorius, as another informs us) be pleased to affirm, that the loadstone declines as many degrees, as the pole-star is distant from the pole of the world; yet besides many reasons, common experience sufficiently manifests the inconsiderableness (not to speak more harshly) of that assertion.  For about the islands of the Azores, especially that of Corvo, over which the first meridian is by many supposed to pass, the magnetic needle has been observed directly to respect the poles, without any sensible declination from them, but in other places it is wont to vary sometimes eastward, sometimes westward, more or less.  Insomuch that not only our venturous countryman Captain Thomas James[^6] observed it in 63 degrees north-latitude to be no less than 27 degrees, 48 minutes; but a learned mathematical writer, that is lately come forth, makes the declination at the Fretum Davis to amount to, what is almost incredible, 50 degrees.  And this deflexion of the needle sometimes to one side of the meridian, sometimes to the other, happens with so much seeming irregularity, as has made both the diligent Kircher himself, and many other magnetic writers, almost despair of reducing these kind of observations to any general hypothesis.

[^5]: [original footnote] Fournier Hydr. l. 13, c. 11.

[^6]: [original footnote] In the Table annexed to his voyage

To which we may add, that perhaps very few even of the exactest observations of this nature made an age since, would now appear accurate to them, that should try them in the self-same places wherein, and the self-same manner after which they were formerly made.  So that the diligentest of those observers would appear to us to have been negligent, if the sagacity of some of their succeeders had not prompted them to suspect, that even in the same place the needle's variation may vary.  And I remember, that having not long since enquired of an English contriver of mathematical instruments for the use of seamen, what he had observed concerning this alteration of the needle's variation, he told me, that by comparing of ancient and modern observations made by himself and other accurate mathematicians at London, he had found the declination constantly to decrease, and, as he conjectured, about 12 or 13 minutes (though that methinks be much) in a year.  And it will be yet more difficult to set down any observation of this nature, which will appear exact to posterity, if that strange thing be true (as it may well be) which was related to Kircher by a friend of his, who affirms himself to have observed a notable change of the needle's variation at Naples, after a great incendium of the neighbouring mountain Vesuvius; which alteration he not absurdly suspects to have proceeded from the very great change made in the neighbouring subterranean parts by that great conflagration.  And it seems the same observation has been taken notice of by mathematicians elsewhere.  For the learned Jesuit Fournier in his French hydrography[^7] tells us in more general terms, that since the incendiums of Vesuvius the declination (of the needle) has notably changed in the kingdom of Naples.  The same author somewhere delivers what (if it be true) is remarkable to our present purpose, in these words:  'There are persons, who have observed, that the same needle, that declined .5 degrees upon the surface of the earth, being carried down very low into certain caves, declined quite otherwise.'  I added those words, if it be true, not to question the veracity of the author, but because it is very possible the makers of the observation (though learned men) may have been mistaken in it, without suspecting themselves in danger of being so.  For I should scarce have imagined, unless my own particular observation had informed me, in how great a variety of stones and other fossiles the ore of iron may lurk disguised: so that it is no way incredible, that knowing chemists themselves, and much more mathematicians and others, not being aware of the observation of what I have newly delivered, may presume, because they saw not in the deep caves abovementioned any minerals like the vulgar iron ore, that there is nothing of that metal there, when indeed there may be enough to occasion that deflexion of the needle; which (especially if it be strongly excited) may be often drawn aside by iron or other magnetic bodies, at a greater distance than those, that have not tried, will be apt to suspect.  Which may perhaps be the reason, why in the little island of Ilva (upon the coast of Italy) where they dig up iron and store of load-stones, of which I have seen in Tuscany of a prodigious bigness, there is indifferent, but neighbouring places, such a strange disparity of the needle's variation as curious men have recorded.

[^7]: [original footnote] Livre [?] 11. chap. 10.

Nor are magnetical and anatomical observations the only ones, which are subject to disagree now and then, without the negligence of those that make them: but I want time, and I fear you would want patience, to consider at present as many of them, as might be easily enumerated to you.

I suppose, Pyrophilus, you may have observed, how I in the past discourse have forborn to insist on medicinal experiments; which I have purposely done, because they are so many, and almost all of them subject to such uncertainties, that to insist on them would require much more time, than my occasions will allow me to spend upon this essay.  And indeed in physick it is much more difficult than most men can imagine, to make an accurate experiment: for oftentimes the same disease proceeding in several persons from quite differing causes, will be increased in one by the same remedy by which it has been cured in another.  And not only the constitutions of patients may as much alter the effects of remedies, as the causes of diseases; but even in the same patient, and the same disease, the single circumstance of time may have almost as great an operation upon the success of a medicine, as either of the two former particulars; as we may elsewhere have occasion by sundry instances to manifest.  But besides the general uncertainty, to which most remedies are subject, there are some few, that seem obnoxious to contingencies of a peculiar nature: such is the sympathetic powder, of which not only many physicians and other sober persons have assured me they had successfully made trial, but we ourselves have thought, that we were eye-witnesses of the operation of it; and yet not only many, that have tried it, have not found it answer expectation, but we ourselves trying some of our own preparing on ourselves, have found it ineffectual, and unable to stop so much as a bleeding at the nose; though upon application of it a little before, we had seen such a bleeding, though violent, suddenly stopped in a person, who was so far from contributing by his imagination to the effect of the powder, that he derided those that he saw apply it to some of the drops of his blood.  Wherefore that the sympathetic powder and the weapon-salve are never of any efficacy at all, I dare not affirm; but that they constantly perform what is promised of them, I must leave others to believe.  But making mention of remedies of this nature, though I am willing, Pyrophilus, to put a period both to your trouble and my own, yet I must not omit to tell you, that whereas the peony-root has been much commended both by ancient and modern physicians of no mean account, as an amulet against the falling sickness, and yet has been by many found ineffectual; we have been apt to suspect, that its inefficacy, if it be but infrequent, might possibly proceed from its having been unseasonably gathered: and when I was last in the west of Ireland, acquainting the most eminent of the Galenists there with my conjecture, he confirmed me in it, by assuring me, that he had often tried the peony root unseasonably gathered without success; but having lately gathered it under its proper constellation, as they speak, (which is when the decreasing moon passes under Aries) and tied the slit root about the necks and arms of his patients, he had freed more than one, whom he named to me, from epileptical fits.  Agreeable whereunto I find, that a famous physician of Grenoble, Monsieur des Grands Prez, in the last of his observations communicated to the famous practical physician Riverius, solemnly professes his having many times freed his patients from the falling-sickness by the single outward application of peony-roots, collected and applied as is above mentioned.  But though he thence infers the usefulness of observing stars in the practice of physic, yet before much weight be laid upon such improbable notions, as most of those of judiciary astrologers, the influence of constellations upon simples, etc. ought by severe and competent experiments to be better made out than hitherto it has been.

But to say no more of the contingent observations to be taken notice of in trials medical, I could tell you, that I have observed even mathematical writers themselves to deliver such observations as do not regularly hold true.  For though it has been looked upon as their privilege and glory to affirm nothing, but what they can prove by no less than demonstration; and though they used to be more attentive and exact, than most other men in making almost any kind of philosophical observation: yet the certainty and accurateness, which is attributed to what they deliver, must be restrained to what they teach concerning those purely-mathematical disciplines, arithmetic and geometry, where the affections of quantity are abstractedly considered: but we must not expect from mathematicians the same accurateness, when they deliver observations concerning such things, wherein it is not only quantity and figure, but matter, and its other affections, that must be considered.  And yet less must this be expected, when they deliver such observations, as, being made by the help of material instruments framed by the hands and tools of men, cannot but in many cases be subject to some, if not many, imperfections upon their account.  Many of the modern astronomers have so written of the spots and more shining parts or (as they call them) Faculae, that appear upon or about the surface of the sun, as to make their readers presume, that at least some of them are almost always to be seen there.  And I am willing to think, that it was their having so often met with such phenomena in the sun, that made them write as they did.  And yet when I first applied myself to the contemplation of these late discoveries, though I wanted neither good telescopes, nor a dark room to bring the species of the sun into, yet it was not till after a great while, and a multitude of fruitless observations made at several times, that I could detect any of these solary spots, which having during many months at least appeared so much more seldom than it seems they did before, that I remember a most ingenious professor of astronomy, excellently well furnished with dioptrical glasses, did about that time complain to me, that for I know not how long he had not been able to see the sun spotted.  And as for the Faculae, that are written of, as such ordinary phenomena, I must profess to you, Pyrophilus, that a multitude of observations made with good telescopes, at several places and times whilst the sun was spotted, has scarce made me see above once any of the looked for brightnesses.

And as the nature of the material objects, wherewith the mathematician is conversant, may thus deceive the expectations grounded on what he delivers; so may the like happen by reason of the imperfection of the instruments, which he must make use of in the sensible observations, whereon the mixed mathematics (as astronomy, geography, optics, etc.) are in great part built.  This is but too manifest in the disagreeing supputations, that famous writers, as well modern as antient, have given us of the circuit of the terrestrial globe, of the distance and bigness of the fixed stars and some of the planets, nay, and of the height of mountains: which disagreement, as it may oftentimes proceed from the differing method and unequal skill of the several observers, so it may in many cases be imputed to the greater or less exactness and manageableness of the instruments employed by them.  And on this occasion I cannot omit that sober confession and advertisement, that I met with in the noble Tycho, who having laid out, besides his time and industry, much greater sums of money on instruments than any man we have heard of in latter times, deserves to be listened to on this theme, concerning which he has (among other things) the following passage:  *Facilè* (says he) *lapsus aliquis penè insensibilis in instrumentis etiam majoribus conficiendis subrepit, qui inter observandum aliquot scrupulorum primorum jacturam faciat; insuper si ipse silus et tractandi modus non tam absoluta norma perficiatur, ut nihil prorsus desideratur, intolerabilis nec facilè animadvertenda deviatio sese insinuat.  Adde quod instrumenta usu et aetate  prima perfectione degenerent.  Nihil enim, quod hominum manibus paratur, ab omni mutatione undiquaque existit.  Organa enim ejuscemodi, nisi è solido metallo affabre elaborentur, mutationi aëreae obnoxia sunt; et si id quoque detur, ut è metallica materia constent, nisi ingentia fuerint, divisiones minutissimas graduum non sufficientur exhibent; dumque hoc praestant, sua magnitudine et pondere se ipsa ita aggravant, ut facile tum extra planum debitum aut figuram competentem, dum circumducuntur, declinent, tum etiam sua mole intractibilia redduntur.  Quare magis requiritur in instrumentis astronomicis, quae omni vitio careant construendis, artificium pari judicio conjunctum, quam haclenus  quamplurimis animadversum est.  Id quod nos ipse usus longaque docuit experientia, non parvo labore nec mediocribus sumptibus comparata.*[^9]
       
[^9]: [original footnote] Tycho Brahe [?] l. 2. de Cometa An. 1577. p 153
       
Hitherto our noble author.  And as for the observations made at sea, the diligent Fournier advertises, that however many sea-captains and others may brag of their mathematical observations made on ship-board, yet he, upon trial of many instruments both at sea and ashore, makes bold to affirm, that no astronomer in the world can be sure to make his observations at sea within ten minutes of the precise truth, no not (says he) upon the sand itself, within one minute of it.

But instead of acquainting you with what may be drawn from the writings of our hydrographer, to prove, that his assertion is rather modest than too bold, I shall observe, that the observations even of skilful mathematicians may hold so little, or disagree so much, when they pretend to give us the determinate measures of things, that I remember of three very eminent modern mathematicians, who have taken upon them, by their experiments, to determine the proportion between air and water, the one makes not the weight of water to exceed about 150 times that of air; the other reckons water to be between 13 and 14 hundred times; and the third no less than 10,000 times the heavier.  Not to mention a modern and famous writer or two, who have been so mistaken as to think, that the weight of the water in comparison of the air is I know not how much under-reckoned, even by this last (overbold) estimate.  And, if I had leisure, I could annex an experiment partly statical, and relating to the weight of the air, which though we made many times in an hour, yet we missed of the like success twice as often in the same hour, without being able to know beforehand, whether the experiment would succeed within some pounds weight.  But of this more perhaps elsewhere.

The ends, Pyrophilus, which we have proposed to ourselves in setting down the things by us delivered in this and the former essay, are principally two.

And first, we desire, that the instances we have given you of the contingency of experiments, may make you think yourself obliged to try those experiments very carefully, and more than once, upon which you mean to build considerable super-structures either theoretical or practical; and to think it unsafe to rely too much upon single experiments, especially when you have to deal in minerals: for many to their ruin have found, that what they at first looked upon as a happy mineral experiment, has proved in the issue the most unfortunate they ever made.  And I remember, that the most experienced mineralist I have hitherto been acquainted with, though his skill has been rather gainful than prejudicial to him, has very seriously told me, that he could quickly grow an extraordinary rich man, if he could but do constantly whatsoever he has done, not only two or three, but many times.

The other end, Pyrophilus, to which I had an eye in writing the past discourses, was, that they may serve for a kind of apology for sober and experimental writers, in case you should not always upon trial find the experiments or observations by them delivered answer your expectations.  And indeed it would prove a great discouragement to wary and considerate naturalists from enriching the world with their observations, if they should find, that their faithfulness in setting down what they observed is not able to protect them from blasting imputations of falsehood, but that by publishing anything for the good of others, they must expose their reputation to all the uncertainties, to which any of their experiments may chance to prove obnoxious.  It is true indeed, that if a writer be wont to be fabulous or transcriptive, and to deliver things confidently by hear-say, without telling his readers when he does so; if his experiments upon trial succeed not, we may be allowed to impute their unsuccessfulness rather to him, than to ourselves, or to chance, and need not think ourselves obliged to have so much a greater care of his reputation, than he had of his own, as for his sake to try more than once, what he for our sakes never tried so much as once.  But if an author, that is wont to deliver things upon his own knowledge, and shows himself careful not to be deceived, and unwilling to deceive his readers, shall deliver anything, as having tried or seen it, which yet agrees not with our trials of it; I think it but a piece of equity, becoming both a Christian and a philosopher, to think (unless we have some manifest reason to the contrary) that he set down his experiment or observation as he made it, though for some latent reason it does not constantly hold; and that therefore though his experiment be not to be relied upon, yet his sincerity is not to be rejected.  Nay, if the author be such an one, as has intentionally and really deserved well of mankind, for my part I can be so grateful to him, as not only to forbear to distrust his veracity, as if he had not done or seen what he says he did or saw, but to forbear to reject his experiments, till I have tried, whether or no by some change of circumstances they may not be brought to succeed.  Thus a while since finding in Sir Francis Bacon, that he delivers as a somewhat unlikely truth, that spirit of wine will swim upon oil (of almonds) we forthwith made trial of it, but found the oil swim upon the spirit of wine, and this upon several trials before witnesses: but our tenderness of the reputation of so great and so candid a philosopher made us to bethink ourselves, that (though he mentions it not, nor perhaps thought of any such thing, yet) possibly he may have used spirit of wine more pure than ordinary; and thereupon having provided some that was well rectified, we found, that the oil, that was wont to swim upon spirit of wine, not freed from its aqueous parts, did readily sink, and quietly lie in the bottom of that, which was carefully dephlegmed.  And so having been informed, that the learned Dr. Brown somewhere delivers, that aqua fortis will quickly coagulate common oil, we poured some of those liquors together, and let them stand for a considerable space of time in an open vessel, without finding in the oil the change by him promised (though we have more than once with another liquor presently thickened common oil).  Whereupon being unwilling, that so faithful and candid a naturalist should appear fit to be distrusted, we did again make the trial with fresh oil and aqua fortis in a long-necked phial left open at the top, which we kept both in a cool place, and after in a digesting furnace; but after some weeks we found no other alteration in the oil, that that it had acquired a high and lovely tincture: notwithstanding which, being still concerned for the reputation of a person, that so well deserves a good one, the like contingencies we have formerly met with in other experiments, made us willing to try, whether or no the unsuccessfulness we have related might not proceed from some peculiar though latent quality, either in the aqua fortis or the oil by us formerly employed: whereupon changing those liquors, and repeating the experiment, we found after some hours the oil coagulated almost into the form of a whitish butter.  Nor dare I allow myself to be confident, that I shall not need to be dealt with by you upon some occasions, with the like equity, that I have been careful to express towards others.  And since the writing of thus much of this very essay, having desired a very skilful and candid chemist to do me the favour to provide me some of the purest and strongest spirit of salt, that could be made; he kept some salt in a vehement fire for many days and nights together, and freed the extracted liquor so carefully and so skilfully both from its phlegm and its terrestrial faeces, that after all I have written in the former essay concerning the menstruum, I must freely confess to you, that I am now satisfied, that a spirit of sea salt may without any insincerity be so prepared, as to dissolve the body of crude gold, though I could not find, that the solutions I made of that metal were red, but rather of a yellow or golden colour, much like those made with common aqua regis.  But neither this artist nor I have been since able to make another spirit of salt capable of dissolving gold, notwithstanding all the industry we have employed about it; which makes me refer this to contingent experiments; unless the prosperous event of our former trial may be ascribed to the quality of the salt, that was distilled, which was brought from the island of Mayo, where the scorching sun makes out of the sea-water a salt, that is accounted much stronger and more spirituous than that, which is wont to be made in France and other more temperate climates.  And let me, Pyrophilus, take this opportunity to add, that if I had not very cautiously set down the observation I related in another essay[^10] concerning the little fishes or worms I there teach you to discover in vinegar, I should perhaps need much of your equity, to keep me from being thought to have imposed upon you in what I there delivered.  For I have since met with many parcels of vinegar, wherein the observation could not be made, for one wherein it held; so that I am glad to keep by me some vinegar stocked with those scarce visible animals, to satisfy ingenious men, among whom some have been fain, after their own fruitless trials, to come to me to show them the things delivered in that observation.  What I mentioned a little above to have been tried upon sallet-oil, puts me in mind of telling you, that among our experiments concerning the changes of colours, we were about to acquaint you with one, which we had formerly made upon common oil-olive, it seeming to us a not inconsiderable one; since it was a way, that we devised of instantly changing the colour of the oil from a pale yellow to a deep red, with a few drops of a liquor, that was not red, but almost colourless.  This experiment, as we were saying, Pyrophilus, we were about to set down among others concerning colours: but because we do not willingly rely on a single trial of such things, as we know not to have been ever tried before, we thought it not amiss for greater security to make the experiment the second time, but could not then find it to succeed, nor even since upon a new trial (probably by reason of some peculiar quality in that particular parcel of liquor we first made use of) which made us think fit to omit the intended mention of it: but if I had upon my first trial acquainted you with it without any further scruple, you might upon trial have suspected, if not concluded, that I had misinformed you, though I had really delivered nothing but what I had tried.  And indeed, Pyrophilus, though I have not the vanity to pretend to have deserved so much of you, as such naturalists as Sir Francis Bacon have deserved from every ingenious reader of their books; yet perhaps you will do me but right to believe, that though some of the experiments I have delivered may prove contingent, yet I have not delivered them unfaithfully, in reference to what I thought I observed in them, and remembered of them.  And though I desire you should so read my writings, as to give no farther assent to my opinions, than the reasons or experiments produced on their behalf require; yet in matters of fact, which I deliver as having tried or seen them, I am very willing you should think, that I may have had the weakness to be mistaken, but not an intention to deceive you.

[^10]: [original footnote] This is one of those, that make up the book of the usefulness of Experimental Philosophy.


There is yet one thing more, that I shall venture to acquaint you with before I conclude this essay, though you may think it relishes of a paradox, and it is this: that when I am satisfied of the abilities and circumspection of a writer, delivering a matter of fact as upon his own knowledge; I do not presently reject his observation as untrue, much less condemn the person himself as a liar, whensoever I find, that it seems to be contradicted by a contrary and more undoubted observation, or to contradict a received and plausible either hypothesis or tradition; but rather try, if by fit distinction or limitation I can reconcile them; unless I can imagine something or other, which might probably lead him to mistake.  And of this indulgence to an intelligent writer I have this reason to give, that sometimes there happen irregularities contrary to the usual course of things, as is evident in monsters; and sometimes the received hypothesis, though perhaps not to be rejected as to the main, will not hold so universally as men presume; and sometimes too the contradiction between the observations may be but seeming (by reason of the want of some unheeded circumstance necessary to make them inconsistent) and so they may both be true.

We might dilucidate and confirm what we have newly delivered by several instances, were it not, that this essay is already but too prolix.  Wherefore we shall only recommend to your consideration these few particulars.

That the Irish spiders (of which, whatever is vulgarly believed to the contrary, myself have in Ireland seen many) are not poisonous, is not doubted by the inhabitants, who have had many ages experience of their harmlessness: and yet I dare not deny what the learned Scaliger somewhere affirms, that in (his country, if I mis-remember not) Gascony their venom is so pernicious, that they sometimes poison those that treat upon them through the very soles of their shoes.  And that even here in England (though a country so near to Ireland) some spiders (at least) are venomous even without biting, I may elsewhere have occasion to give you an experimental proof.

It is so much taken for granted by many authors, who pretend likewise to give reasons of it, and by the generality of their readers, that under the same meridian the magnetic needle keeps everywhere the same variation, without changing it by being carried northwards or southwards, that it is like, if many persons better acquainted with magnetic speculations than trials should read in the relations of the Hollanders, that under the meridian, that passes by the island of Corvo, where the needle points directly at the poles, and which is therefore wont to be reckoned the first meridian, they found at two places, the one about 46, the other about 55 degrees of northern latitude, a declination in the former of those elevations of no less than 7 or 8 degrees, and in the latter of a far greater number; and also that they found under the twentieth parallel of southern latitude under the same meridian of the Azores 10 or 11 degrees of declination; many, I say, if they should meet with these particulars, probably would suppose the Dutch to have been very bad observers, because these observations do not (as we intimated above) agree with the theory of the needle's declination.  And yet if we confer these observations with others of the like nature, made by good navigators and other skilful men along other meridians, we may, I suppose, find cause rather to rectify the general opinion, than reject the Dutch observations for their disagreeing with it; especially if we take into consideration what is affirmed by the Jesuit Jules Alenis (whom Fournier, amply treating of longitudes, extols for the most accurate observer of the needle's variation that ever was) sailing into China in a great Portugal carraque, and accompanied by the famous pilot Vincent Rodrique, who had then made twenty-eight voyages to the Indies.  For out of one of this father's letters Fournier has preserved this memorable passage:  'You must' (says he) 'take notice of one thing very considerable, namely, that the further you go from the equator in the same meridian, the greater you will find the magnetical variation.'[^11] There are some eminent modern naturalists, who affirm, that they have assuredly tried by weather-glasses, that cellars and other subterranean places are colder in winter than in summer: and yet not to oppose to this experiment the common tradition to the contrary, I remember, that the bold and industrious Capt. James (formerly mentioned) in the relation of his strange voyage published by his late Majesty's command, had this notable observation, where he relates the excessive coldness of the water they met with in summer in that icy region, where they were forced to winter in the year 1632.  'Moreover our well (says he) out of which we had water in December, had none in July.'

[^11]: [original footnote] De la Longitude, c. 34 [?].

Lastly, though in the western parts it have been observed, that generally the inside, or heart, as they call it, of trees, is harder than the outward parts; yet an author, very well versed in such matters, treating of the building of ships, gives it us for a very important advertisement touching that matter, that they have observed at Marseilles, and all along the Levantine shores, that that part of the wood, that is next the bark, is stronger than that, which makes the heart of the tree.[^12] But to draw at length to a conclusion of this already too tedious essay; the ends above mentioned, Pyrophilus, being those, which I proposed to myself in writing the past discourse, you will make an use of it, which I was very far from intending you should, if you suffer it to discourage you from the vigorous prosecution of your inquiries into experimental knowledge.  Nor indeed is anything, that has been said, fit to persuade you to other than watchfulness in observing experiments, and wariness in relying on them; but not at all to such a despondency of mind, as may make you forbear the prosecution of them: for neither doth the physician renounce his profession, because many of the patients he strives to cure are not freed from their diseases by his medicines, but by death; nor doth the painful husbandman forsake his cultivating of the ground, though sometimes an unseasonable storm or flood spoils his harvest, and deprives him of the expected fruit of his long toils.  For as in physic and husbandry, those, that exercise them, are kept from deserting their professions, by finding, that though they sometimes miss of their ends, yet they oftentimes attain them, and are by their successes requited not only for those endeavours that succeed, but for those that we lost; so ought we not by the contingencies incident to experimental attempts, to be deterred from making them, because not only there are many experiments scarce ever obnoxious to casualties, but even among those, whose event is not so certain, you may very probably make an experiment very often, without meeting with any of those unlucky accidents, which have the power to make such experiments miscarry.  And sure the prosperous success of many succeeding attempts is well able to make amends for the fruitless pains employed on those few, that succeed not; especially since in experiments it not frequently happens, that even when we find not what we seek, we find something as well worth seeking as what we missed.  Of this last mentioned truth we may elsewhere have occasion to discourse more largely; and therefore shall now conclude with barely minding you, that even merchants themselves are not wont to quit their profession, because now and then they lose a vessel at sea, and oft times their ships are by contrary winds and other accidents forced to put in at other ports than those they were bound for.  Which example I the rather make use of, because that as the American navigators employed by the European merchants, having been by storms forced from their intended course, have been sometimes thereby driven upon unknown coasts, and have made discovery of new regions much more advantageous to them, than the fairest and most constant winds and weather could have been; so in philosophical trials, those unexpected accidents, that defeat our endeavours, do sometimes cast us upon new discoveries of much greater advantage, than the wonted and expected success of the attempted experiment would have proved to us.

[^12]: [original footnote] Fourn. Architecture Navale [?], c 22.

