---
title: "The Unsuccessfulness of Experiments (I)"
author: "Robert Boyle (1627-1691) [edits by Richard D. Morey]"
output: tint::tintPdf
latexfonts: 
  - package: lato
    options: default
  - package: FiraMono
linkcolor: "0.3,0.3,0.6"
---

```{r setup, include=FALSE}
library(tint)
# invalidate cache when the package version changes
knitr::opts_chunk$set(tidy = FALSE,
                      cache.extra = packageVersion('tint'),
                      echo=FALSE)
options(htmltools.dir.version = FALSE)

margin_note = function(text, icon = "&#8853;"){
  in_file = tempfile( fileext = ".md")
  out_file = tempfile( fileext = ".tex" )
  cat(text, file = in_file)
  rmarkdown::render(input = in_file,
                    output_file = out_file,
                    output_format = "latex_fragment", quiet = TRUE)
  rendered_text = paste(readLines(out_file), collapse = "\n")
  tint::margin_note(rendered_text, icon)
}

```

`r margin_note("Within the text, I have changed some archaic words or phrases to those that will be clearer to the modern reader. Most of his elaborate grammar remains. ---RDM")`

I am very sorry, Pyrophilus[^pyrop], that to the many (elsewhere enumerated) difficulties which you may meet with, and must therefore surmount, in the serious and effectual prosecution of experimental philosophy, I must add one discouragement more, which will perhaps as much surprise you as dishearten you; and it is, that besides that you will find (as we elsewhere mention) many of the experiments published by authors, or related to you by the persons you converse with, false or unsuccessful (besides this, I say) you will meet with several observations and experiments, which, though communicated for true by candid authors or undistrusted eye witnesses, or perhaps recommended to you by your own experience, may upon further trial, disappoint your expectation, either not at all succeeding constantly, or at least varying much from what you expected.
 
[^pyrop]: Boyle is addressing his essay to an imaginary student named Pyrophilus, like a modern senior scientist might write an open letter to early career researchers. ---RDM

This warning may seem of so discouraging a nature, that I should much scruple the giving it you, but that I suppose the trouble at that unsuccessfulness, which you may meet with in experiments, may be somewhat lessened by your being forewarned of such contingencies: and that if you should have the luck to make an experiment once, without being able to perform the same thing again, you might be apt to look upon such disappointments as the effects of an unfriendliness in nature or fortune to your particular attempts, as proceed but from a secret contingency incident to some experiments, by whomsoever they be tried.[^a]

[^a]: Boyle is emphasising to Pyrophilus that sometimes you don't need an explanation for a "unsuccessfulness" other than chance. We should inferring avoid complicated "secret contingencies" (in today's language, "hidden moderators").  ---RDM
       
But because, Pyrophilus, the advertisement, which I am about to give you, may seem, as paradoxical, as discouraging: it will be but reasonable, that I present you with some instances of the requisiteness of it: which I shall the more willingly do, because thereby I may not only evince the truth of it, but somewhat lessen the despondency it is apt to produce, by letting you see, that though some of your experiments should not always prove constant, you have many partners in that infelicity, who have not been discouraged by it.[^b]
       
[^b]: Normalizing failures to replicate is important to science not only because publishing them means a more accurate scientific record, but also because it is crucial that early career researchers not be discouraged by their own failures. This has been a much-discussed aspect of the replication crisis. ---RDM

To make nice and curious distinctions of the several grounds and occasions of the unsuccessfulness of experiments, would, perhaps, prove a work of greater difficulty than use; and therefore I shall content myself grossly to distinguish the causes of that unsuccessfulness, into the particular or mistaken properties of the materials employed about them, and some such error committed in the handling of these materials, as though it hinder the success of the experiment, is not easy to be discerned.  Which therefore I mention, that I may distinguish these kind of errors, that I am now to consider, from those more obvious ones, which proceeding barely from the unskillfulness of the tryers of the experiments, may be easily enough discerned, and either rectified or avoided by a knowing artist, or a person well-versed and expert in making those particular experiments, which through that unskillfulness may have miscarried.[^c]
    
[^c]: Boyle distinguishes two broad reasons for failure: first, deeper misunderstandings inherent to the area of study (in his case, composition of materials); and second, mere methodological errors arising from lack of expertise. ---RDM
   
The materials to be employed about the experiments we are considering may also admit of several distinctions; as into natural and synthesized, pure and contaminated, simple and compound, etc.  But we shall likewise purposely avoid insisting on any of these, and content ourselves to cast what we have to say on this part of our theme into a few and comprehensive observations.
       
And in this first place we will observe, that different experiments succeeded not, because they were at one time tried with genuine materials, and at another time with contaminated[^e] ones: and in this case it may be all one, as to the event of the experiment, whether the materials, wherewith it was successfully tried, were contaminated or not, if those made use of in the latter trial were of differing qualities from those employed in the former; because it may very well happen, that contaminated bodies (as we may have occasion to show hereafter) by the addition of those things, or by that deceitful way of preparation, whereby they have been contaminated, may acquire an aptitude to produce such effects, as, had they not been adulterated, they would not have been fit to do.  Now it is scarcely imaginable to him, that has not been very conversant with the drugs and simples sold in shops, how generally they are adulterated by the fraudulent avarice of the sellers, especially if they be such, whose preciousness may make their contamination very beneficial to them that practice it.  It has been lately much complained of by some of the cultivators of clover-grass, that from much of the feed no grass sprung up; which not being attributable to the soil nor the sower, proceeds---as some analogical observations make me suppose---from the effeteness (if I may so speak) of the old seed sometimes sold in the shops.  And upon this subject I cannot conceal from you what was lately affirmed to me by one of the most eminent and soberest chemists of Amsterdam, who was also an Indian merchant, who assured me, that the most of the cinnamon and cloves, that is brought into these western regions, is defrauded in the Indies of much of the finest and subtlest aromatical parts, before it be sent into Europe.  And to give a more familiar instance to our present purpose, you may be pleased to remember, Pyrophilus, that in one of the first of these essays, we have made mention to you of great store of living creatures, which we had observed in vinegar;[^f] of the truth of which observation we can produce many learned and severe witnesses, who were not to be convinced of it, until they had seen it themselves: and yet, Pyrophilus, there are many parcels of excellent vinegar, wherein you may in vain seek for these living creatures: and we are now distilling some of that liquor (which if we did not think to be of the strongest and best sort, we should scarce think worth the being distilled for spirit) wherein nevertheless we can neither by candle-light nor by day-light discern any of those little creatures, of which we have often seen swarms in other vinegars.  Of such fraudulent tricks as those lately mentioned, I could easily give you many instances, if I were not afraid of teaching fallacies by discovering them.  But some are so notorious, or otherwise of such a nature, as that it may be more useful than dangerous to mention them.

[^e]: It must be emphasized that in the seventeenth century, chemistry was arising from alchemy. Scientists at the time were attempting to understand how materials were composed, so the idea of a "pure" material was not based on a comprehensive chemical theory. Such a theory lay well over a century in the future. Imagine trying to understand what the purity of a material meant for an experiment, without understanding chemical elements. For Boyle and contemporaries, impurities were more than in inconvenience; the issue of purity was inextricably linked to the very questions they were trying to answer.  ---RDM

[^f]: In the seventeeth century, Robert Hooke found tiny "eels" (nematodes) in some vinegar with his new microscope. Unsurprisingly, many people didn't believe it.  ---RDM
       
It is commonly known, that sublimate is wont to be contaminated with arsenic: and how differing the effects of such sublimate may be from those of that, which is faithfully prepared, not only upon metals, but (when mercurius dulcis`r margin_note("Mercurous chloride was known to alchemists as 'mercurius dulcis'. ---RDM")` and other preparations are made of it) upon human bodies, they, and scarce any but they, who are acquainted with the noxious qualities of arsenic, both to metals and men, can readily imagine.  And indeed as for chemical preparations, Helmont[^1] was not much in the wrong, when he affirmed, there were scarce any, vulgarly sold in shops, to be relied on as faithfully prepared.  And for my part, I have so often met with chemical preparations, which I have found impure, that I dare scarce trust any, either in the administration of physic, or so much as in the trial of considerable experiments, which either my own furnaces do not afford me, or wherewith I am not supplied by some person, of whose skill and faithfulness I have a good opinion. The other day, having occasion to use some spirit of salt`r margin_note("'Spirit of salt' is hydrochloric acid. ---RDM")`, whereof I was not then provided, I sent for some to a chemist, who making it himself, was the likelier to afford that, which was well made: but though I gave him his own rate for it, at the first rectification even in a retort`r margin_note("A [retort](https://en.wikipedia.org/wiki/Retort) is a special vessel for chemical experiments. ---RDM")`, a single pound afforded us no less than six ounces of phlegm; and afterwards being further rectified in a high body and gentle heat, the remaining spirit parted with a scarce credible quantity of the like nauseous liquor, and after all these sequestrations of phlegm, was not pure enough, to perform what we expected from it.  Of which complaining to an excellent chemist of my acquaintance, he sent for spirit of salt to a very eminent distiller of it, who gets much by his profession, and passes for a very honest man: but this spirit, besides its weakness, discovered itself to be contaminated with either spirit of nitre, or aqua fortis`r margin_note("Nitric acid was known to alchemists as 'aqua fortis' or 'spirit of nitre'. ---RDM")`, which betrayed itself by its peculiar and odious smell; whereas spirit of salt skilfully and sincerely drawn is commonly of a greenish colour, bordering upon yellow, and has usually a peculiar, and sometimes (as I can exemplify to you in some of mine) a not unpleasing smell.  And let me on this occasion advertise you, Pyrophilus, that in [many different] cases it is not enough to separate the aqueous parts by dephlegmation, as many chemists content themselves to do; but some liquors contain also an unsuspected quantity of small corpuscles of somewhat an earthy nature, which being associated with the saline ones, do clog or blunt them, and thereby weaken their activity: and therefore such liquors to be well depurated require the being distilled off, and that with a slow fire, that the dry faeces may be left behind in the bottom of the glass.  To satisfy some persons, that this observation is not groundless, we have sometimes taken of the better sort of spirit of salt, and having carefully dephlegmed it, removed it into lower glasses (that the less heat will suffice to make the liquor ascend) and having gently abstracted the whole spirit, there remained in the bottom and the neck of the retort, whence it was distilled, so great a quantity of a certain dry and stiptical substance, for the most part of a yellowish colour, that it seemed strange to the beholders, that so clear a spirit should conceal so much of it: and we ourselves should have wondered at it too, had we not remembered, that in what the chemists are wont to call the oil or rectified butter of antimony`r margin_note("[Butter of antimony](https://en.wikipedia.org/wiki/Antimony%5Ftrichloride) is antimony trichloride. ---RDM")` made with sublimate, the liquor, though distilled and very limpid, almost like fair water, consists in great part of the very body of the antimony: which we would here manifest, but that we elsewhere do it; and therefore choose rather in this place to take notice, that the spirit of salt after this second depuration was so changed, that it seemed to be a much nobler, and almost another liquor than it was before.
       
[^1]: [original footnote] Accipe pulverem Johannis de Vigo propria, manu paratam, nam alioquin admistus minio est adulteratus, prout qualecunque medicamen chymicum quod venale exstat fraude plenum est.  Helmon. de Febr. c. 14. Sunt nempe olea essentialia venalia, quoque mange aere penduntur, adulterata omnia atque singula, etc. Idem de Feb. c. 15.
       
But to return to our contaminated spirit; what differing effects would be produced by true spirit of salt, and that which is mixed with the spirit of nitre, he that knows the great disparity in the operations of those two liquors, whereof (to mention now no other instances) the former will precipitate silver, when the latter has dissolved it, may easily inform you.  Which instances I mention not as the [most important], which may be produced on this subject, but as the freshest in my memory.

In the next place, Pyrophilus, I observe, that even when the materials employed about experiments are no way contaminated, but genuine, and such as nature has produced them, or art ought to prepare them; even then, I say, there may be a very considerable disparity between concretions of the same kind and name, and which pass without suspicion for bodies of perfectly the same nature.
       
This may, to you, Pyrophilus, seem a great paradox; but perhaps upon examination it will appear a great truth: which because I am, perchance, the first, that has solemnly asserted, I hope I shall obtain your pardon, if I insist somewhat the longer upon the making it out.  For though antimony (and the like is to be understood of quicksilver, gold, copper, tin, etc.) is wont by almost all men without hesitancy to be looked upon as being all of it of the same nature as well as denomination; yet he, that will take the liberty to suspect, that they may be deceived in that opinion, and then heedfully observe the differing progress and event of experiments, may very well discern, that there is as well a difference in minerals of the same kind, as there is in vegetables and animals of the same species.  And as the white rose, the red rose, and the damask rose differ much from one another, though all three be roses; and as the sour and sweet orange are very differing between themselves, and yet both of them from the China orange, though all be oranges; and as the hound, the grey-hound, the spaniel, the tumbler, the mastiff, and the water dog, etc. are very diversely qualified, though all of them be dogs: so neither are all the parcels of antimony to be met with in mines or shops of altogether the same qualities, though all of them be antimonial concretes.  There is indeed this difference between the variety to be observed in vegetables and animals, and that which is to be found in minerals, that the former is wont to be more obvious to the eye, and betray itself by some difference to be observed, either in the size of creatures of the same kind, or in some peculiar shape or colour, by which it is easy for nature conspicuously to discriminate bodies, that consist of many discernibly distinct parts; whereas minerals appearing to the eye either to be perfectly similar, as metals, or at least to consist but of two or three distinct ingredients as [cinnabar](https://en.wikipedia.org/wiki/Cinnabar), and some other mineral concretions, the diversity to be found between minerals of the same denomination is hardly to be discerned, before experience have discovered it.

And on this subject I consider, that the womb (if I may so speak) of a mineral body is not always like that of an animal, a place by a competent and peculiar involving fence secured from the intrusion of all bodies not of kin to that included in it: but a mineral being generated in the bowels of the earth, its womb is oftentimes accessible and open to other mineral juices or steams, that pass that way, though of never so differing natures from that of the more copious mineral.  Insomuch that not only I have had the opportunity to observe (not without some wonder) minerals of differing kinds, as [marchasites](https://en.wikipedia.org/wiki/Marcasite) and metals, [marchasites](https://en.wikipedia.org/wiki/Marcasite) and stones, (I mean stones properly so called) salt and sulphur, and the like, blended in the same small lump of matter; but I have sometimes found, in a great mass of one sort of mineral, small parcels of a mineral of a quite differing kind perfectly enclosed in the substance of the other.  But to resume what we were saying before, these intruding bodies (if I may so speak) being coagulated, and perhaps ripened together with the former by length of time, are not easily either separable, or so much as distinguishable at their first digging out of the ground, and much less after their liquification.  For the ignorant or heedless miner aiming only at the obtaining a quantity of such a metal, or other mineral, as may be marketable under such a determinate name, has neither the design, nor perhaps the skill, to make nice separations of the heterogeneous bodies to be met with in his ore, but melts so much of them as he can promiscuously together, and then sells them, not only to the merchant, but the chemist, for that metal or mineral, whose outward form and properties (as colour, consistence, weight, sound, etc.) it has: though that metal, under whose name it passes, be indeed but the predominant ingredient of the lump, wherein many other minerals may in small quantities lie concealed, and yet upon occasion be discovered by exquisite separations, or discover themselves by unexpected operations, when they meet with bodies fit to act on them, or disposed to receive impressions from them.
      
I was lately visited by an ingenuous goldsmith of my acquaintance, who complained to me, that being wont to buy parcels of gold brought in small pieces, and as it were sandy corpuscles, from Guinea, or some country of that coast, though he found it upon all trials very right gold, yet was it so very pale, that few but expert goldsmiths would meddle with it, as fearing it had been some contaminated metal; adding, that this exceeding paleness of it sometimes reduced him to melt it with very high coloured gold, or to heighten its tincture with that of copper, to bring it to the colour of ordinary gold.
       
The probability of this may be proved by what is related by Monsieur Flacourt, governor of the French plantation in Madagascar, who, in his newly published history of that island,[^2] speaking of the metals of it, says, Il y a bien, etc. that is, there is certainly gold among the inhabitants of Madagascar, which has not been brought hither by foreign ships: for it is not possible, that such ships should have left them so much of that metal as they have; and besides, it is of a differing nature from that of Europe, which they call in this country *Voulamene Voutroüa*.[^h]  He adds, that this gold, which they call gold of *Malacasse*, is pale, and is not worth above ten crowns (or about fifty shillings) an ounce; also, that the Negroes affirm, that there are many mines of it in the country, where it was formerly dug; that there are three sorts of it differing in fineness from each other, and discriminated by the natives by three peculiar names.  But that which he adds as most considerable, is, *that Malacassean gold is of so easy a fusion, that it is almost as easily melted as lead;* whereas we here find the gold we deal with to require considerably strong fires, and are wont to case in borax to facilitate the fusion.
       
[^2]: [original footnote] *Histoire de Madigascar*, c. 37.
       
[^h]: Lewis (1826) suggests that this pale gold actually contained silver. Boyle says that "upon all trials [it was] very right gold" but without a chemical theory, how was Boyle to know he just didn't have the right experiment to tell? (Lewis, W., 1826. On the mineral history of gold, and on the separation of it from earthy and stony bodies by water, mercury, &c. *Journal of the Franklin Institute*, 2(2), 79--81.) ---RDM
       
Having, upon occasion, had the curiosity not long since to visit some mines of lead, and other metals, I find that there is a great difference, and discernible even to the eye, between the several ores; for instance, of lead, some of which I can show you so like steel, and so unlike common lead-ore, that the workmen upon that account are pleased to call it steel-ore[^i], which being of more difficult fusion than ordinary, they are wont to mix it with other ore, which they call firm-ore, to facilitate the melting of it.  And I likewise took notice of an ore, which for its aptness to [vitrify](https://en.wikipedia.org/wiki/Vitrification), and serve the potters to glaze their earthen vessels, the miners call pottern-ore, and sell it (at least where I saw it dug up) dearer than other ore, from which it differs both visibly enough, and as the workmen affirm, in many other (and those less obvious) qualities; and yet all these ores, after fusion, do pass indiscriminately under the name and notion of lead.[^j]  In which therefore it is no wonder, that severer inquiries find a great deal of disparity.  I remember I did not long since cause some lead-ore to be tried, which being the most promising that ever I saw, made me suppose it might contain some considerable quantity of silver:  but though it proved so rich in lead, as to yield after the rate of seventy pound to the hundred, yet one of the most expert artists in Europe could not extract one grain of silver out of it; whereas the lead of very many mines, being skilfully examined, will leave behind it, upon the test, a proportion of pure silver.  And though this quantity of silver be not considerable enough to make such mines as yield it pass for silver mines, (or, as we are wont to call them, mines-royal) because the silver will not justify the cost of extracting it; yet such mines, though they pass but for lead mines with the metal worker, may appear to be mixed mines to the naturalist, who may meet with many different experiments, wherein the little silver that is in them, may make their lead operate differently from that of those ores, which are wholly destitute of silver.

[^i]: This appears to be a reference to a particular variety of [galena](https://en.wikipedia.org/wiki/Galena). Galena contains silver. ---RDM

[^j]: With a chemical theory, one could explain these differences; without one, how is one to say whether they are the same material or not? One can only hope to find an experiment that differentiates the materials somehow, and to later explain through theory. ---RDM

And as this disparity is discernible in lead-ores, so it may well be supposed, that the like would be discovered in the ores of other metals, if they were but purposely and skillfully examined.  On which subject I remember, that a very experienced person in these affairs, and otherwise very candid and sober, was lately very desirous I should procure him some tin-ore, alleging, that he had met with a sort of it, which, after a long digestion in [lixiviate](https://www.merriam-webster.com/dictionary/lixiviate) liquors, afforded him a very considerable proportion of the richer metals; insomuch that having a large quantity of that ore, and finding the experiment on it to succeed constantly, he promised to himself a vast income by it: but when that stock of ore was spent, the next that he procured, though with great carefulness managed as the former, would by no means be brought to afford either so considerable a benefit, or so much as any at all.  Which brings into my mind, that having once bought a parcel of block-tin (as the tradesmen call that, which is the most pure or unmixed, and as yet unwrought) I was desirous to try, if I could not make a menstruum to dissolve it in such manner as aqua fortis dissolves silver, and aqua regis gold; `r margin_note("A menstruum is a solvent; 'aqua regis' referred to a mixture of nitric acid and hydrochloric acid, known to dissolve gold. ---RDM")` because chemists are wont to complain, that though they have a menstruum or two that will dissolve crude tin, yet they want one, that will keep it dissolved, and will not, which aqua fortis will, let it fall into a calx`r margin_note("A metal calx is an oxide. The chemical reaction referred to here is nitric acic and metallic tin, which produces the calx stannic oxide. ---RDM")`.  Having therefore (by a way that I elsewhere teach) prepared such a liquor as was desired, I evaporated a solution of the aforementioned tin, and setting it to shoot, found somewhat, to my wonder, that the crystals it afforded were not at all like any kind of vitriol `r margin_note("Vitriol is a sulfate. ---RDM")`, but broad, flat, and exceeding thin, just like those of silver.  Whereupon for further trial, having examined this salt by the tongue, we found not, that it had any such taste as skillfully made calx of tin in spirit of vinegar`r margin_note("'Spirit of vinegar' is acetic acid and water. ---RDM")`, (wherein it is not every calx of Jupiter `r margin_note("In alchemy, different materials were associated with planets. 'Jupiter' referred to tin. ---RDM")` that is soluble) which (the last time we tried) seemed to us to have, as it were, a iron taste, but such an excessive bitterness as may be met with in the crystals of silver made with aqua fortis.  Finding also this further resemblance between the salts of these two metals, that they did both of them presently dye upon the nails and skin a blackness, that could not in a short time be washed off; we should have suspected, that the menstruum had exalted the metal dissolved in it to a greater [relationship] to silver;[^k] but having afterwards prosecuted the same trial with the same menstruum, and another parcel of block-tin, (the former being casually lost) this metal, though bought very soon after the other, and, as I remember, at the same place, made us conclude, that the event of our trials proceeded from our having lighted upon a lump of tin, that was of a peculiar nature.[^l]

[^k]: We now know this would not be possible. Tin would remain tin in any chemical reaction. ---RDM

[^l]: Here we have Boyle's report of a completely failed replication of what would have been an important experiment. Why did it fail? He does not know, and he has no way of understanding it, except to continue on with experimentation. ---RDM

I remember also, that a while since a learned and inquisitive friend of mine found in his land a parcel of ore, part of which he showed me, and some of which I can show you, but have not yet made trial of it; which seemed to me, among others that looked upon it, to be copper ore, and which did indeed, after fusion, yield very good copper; but the persons, to whom he committed the examination of the mine, being very inquisitive, and extraordinary skillful, they did (as one of themselves immediately after confessed to me) find in that ore, besides the copper, no inconsiderable quantity of silver; and in that silver (having dissolved it in aqua fortis) a considerable proportion of gold.

But to detain you no longer on this subject; give me only leave to strengthen the paradox I have proposed, by the authority of that great and candid chemist Basilius Valentinus, who speaking of antimony, after he has told us, that there are several kinds of it, and especially two; the one more mercurial, and of a golden property; witnessed by the shining streaks or beams it abounds with; the other more full of sulphur, but destitute of the golden nature that enriches the former; adds, that there is such a different goodness between the several sorts of antimony, as there is between the several sorts of flesh or fish, which, though agreeing in name, and, if you please, in nature, do exceedingly differ in point of goodness.  Which brings into my mind the great difference which I have found, even visible to the eye, between the several sorts of antimony; and makes me also remember, that the other day being by an excellent chemist showed a parcel of antimony as a rarity, upon the score of the various coloured sulphur, wherewith it was conspicuously enriched, the possessor of it soon after employed it to make [butter of antimony](https://en.wikipedia.org/wiki/Antimony_trichloride): but though he were very expert in that kind of distillation, yet instead of the liquor he expected, upon the approach of a gentle fire, he found the neck and body of his retort lined with an antimonial cinnabar, (or at least a red substance, by him concluded to be sulphur;) at which being surprised, he was pleased to withdraw his fire, until he had acquainted me with this accident, and in the yet unbroken retort he showed me the cinnabar, which is not wont (as you know) to arise until after the butter of antimony is come over, and the remaining matter be urged with a vehement fire.  And it is perhaps to the undiscerned difference of antimonies, that we may sometimes ascribe that contingency, which we have many times had occasion to take notice of in the making of antimonial cinnabar: for though in our furnaces it has been very successfully made, yet not only we have afterwards failed of making it, but we have seen much more expert chemists, and who, because of the high value they do (not undeservedly) place upon that medicine, employ themselves oftener than we in making it, many times unsuccessfully attempt the preparing it.[^m]  And it may perhaps also from some diversity either in antimonies or irons, that eminent chemists have (as we have observed) often failed in their endeavours to make the starry regulus of Mars and antimony`r margin_note("In alchemy, iron was associated with the planet Mars. Regulus was metal refined from an ore, and a [stellate regulus](http://webapp1.dlib.indiana.edu/newton/reference/chemProd.do) was a crystal formed of the corresponding material. ---RDM")`.  Insomuch that many different artists fondly believe and teach (what our experience will not permit us to allow) that there is a certain respect to times and constellations requisite to the producing of this (I confess admirable) body.`r margin_note("It may sound ridiculous from a modern perspective, because we have a working chemical theory that does not involve the constellations, but given the difficulties Boyle mentions throughout this essay, it is perhaps easier to see how people trying to decode the 'secret contingencies' hit upon the contellations. Time of year is important to many natural events; why not chemistry?")` Upon which subject I must not omit to tell you, that a while since an industrious acquaintance of ours was working on an antimony, which unawares to him was, as we then supposed, of so peculiar a nature, that making a regulus of it alone without iron the common way, (for his manner of operation I inquired of him) he found, to his wonder, and showed me his regulus adorned with a more conspicuous star, than I have seen in several stellate reguleses of both antimony and Mars. Yet I dare not be too confident that this depended only upon the peculiar nature of that antimony, because since that, my own laboratory has afforded me many such parcels of regulus without Mars, (some of which I have yet by me very fairly stellated) which though made of antimony, that seemed (by its various colours) to be more rich than ordinary in sulphur; yet in regard the antimony did not constantly afford a starry regulus, though by the same person ordered as near as could be after the same manner, it did not so clearly appear to me, whether the different event of the several trials proceeded from the peculiar nature of this or that parcel of antimony, or from some odd and scarce discoverable circumstance in the management of the operation.[^n]  But in either case, the mention of these uncertain events will properly enough belong to our present discourse.

[^m]: Boyle is again suggesting that the variation in experiments is down to true, and interesting, variation in "subspecies" of materials/elements. These variations are due to the formation of the materials in the "womb" of the Earth. This is a deeper point than *just* contamination; rather, he is making a theoretical claim about matter. ---RDM

[^n]: Here, Boyle has reported considerable variation in the results of what appear to be the same experiment. He confesses to uncertainty about the source of the variation. Was it the materials; that is, the composition of the reagents or properties of the antimony sample? Or was it small differences in procedure that matter, but he doesn't know they matter? ---RDM

As in antimony, so (as I intimated above) in [many different] other minerals a considerable diversity may be observed:  and I remember I was lately presented with a piece of a mineral, which to me, as well as to the rest who looked on it, seemed to be an ordinary and worthless [marchasite](https://en.wikipedia.org/wiki/Marcasite); and yet a Dutch merchant (a skillful mineralist) who was the possessor of it, was very industrious to procure a greater quantity thereof, having in some of it, on which he had made trials, found a rich proportion of pure gold.[^o]  And the same gentleman, whose copper ore I formerly mentioned, digging for more of that ore, found lately a quantity of red earth, which by knowing mineralists was guessed to be but bolus `r margin_note("'Bolus' referred to clay, and 'regulus martis stellatus' is crystals of iron refined from iron ore. ---RDM")`, and indeed looked very like it; but being melted with regulus Martis stellatus by a skillful metalurgist, it many times richly recompensed the examiner's curiosity, by affording him many grains of fine gold: and though I doubt, whether this gold proceeded from the bolus, or the regulus melted with it, yet however it may serve for an instance to show, that some mineral bodies, which pass without dispute for minerals of such and such a precise nature, may have lurking in them minerals of a quite other nature, which may manifest themselves in some particular experiments (wherein they meet with proportionate agents or patients) though not in others.

[^o]: This seems unlikely to me, but I am not a chemist. ---RDM

That the talc, which is wont to be employed about cosmetics, is very difficult to calcinate [purify by high temperatures], is so known a thing to those that have tried it, that I have met with good chymists, that have looked on all the calces of talcs but as impostors, Nor indeed have we calcined Venetian talc without some length of time, and much violence of heat.  But among many sorts of talc we have here in England, there is [some?], which a moderate fire will in less than an hour reduce into a snow-white calx, of which I had lately a parcel by me; and some days since I met with another sort of English talc which I could suddenly calcine even with the flame of a candle.  And my experienced friend Dr. K. assures me, that out of a German talc he met with, he did by digesting it in a strong solution of alcalizate salts`r margin_note("Alcalizate salts are [alkali salts](https://en.wikipedia.org/wiki/Alkali_salt).")` separate pretty store of good gold`r margin_note("Gold from talc seems unlikely, so it is unclear to me what Boyle's correspondent actually found. This is the trouble with such anecdotal reports, of course. ---RDM")`, and might have made it a very gainful experiment, if all the talc growing in the same place had been of the same richness.  The like almost has been affirmed to me by a gentleman of eminency, who told me, that from a certain talc he had out of Norway, he had once drawn a pretty quantity of very good gold: and it seems indeed, that though some have been pleased to laugh at all attempts of sequestering anything from any kind of talc; yet some parcels of that mineral afford good store of a tincture, which may, for aught I know, be of a golden nature.  For I remember I have met with a kind of darkish coloured talc (whereof I can yet show you a piece) which when I cast but into aqua regis, the menstruum manifestly worked upon it, and dissolved its coloured parts in such plenty, that the filtrated solution passed without suspicion among many knowing naturalists, to whom I showed it, for a fair solution of gold.  Paracelsus[^3] himself reckons four kinds of talc, red, white, black, and of that colour, which his interpreter translates [luteous](https://www.merriam-webster.com/dictionary/luteous): and perhaps each of these colours comprises several kinds of that mineral.  And therefore that mineralist did not amiss, when he added in the same discourse, after he had mentioned great variety of marchasites, stones, and other minerals, Sed et hoc verum est, in terra multa adhuc condi, quae mihi incognita sunt, sed eadem nec alii norunt.  Certum siquidem est, progressu temporis tot tamque varia à Deo adhuc proditum iri, de quibus nemo nostrum nedum unquam somniavit.[^4]
       
 [^3]: [original footnote] Paracel. de Mineral T[r]act. 1.
       
 [^4]: [original footnote] Paracel. Ibidem. [A tentative [translation](https://ask.metafilter.com/343503/What-is-the-best-translation-of-this-from-Latin-to-English), thanks to Metafilter user Maecenas: "And indeed it is true that there are many [minerals] stored in the earth, which are unknown to me and which others also do not know. It is certain that given the progress of time, so many various [minerals] hitherto [unknown] will be brought forth by God, which none of us has scarcely ever dreamed of." ---RDM]      
  
It is well-known, that there is a great difference between vitriols`r margin_note("[Vitriols](https://en.wikipedia.org/wiki/Vitriol) are sulfates.")`, that are reputed to be merely of the same metal.  And not to mention those vitriols, that I have either made or seen, of less usual colours; nor to take notice of the veins, slate, and even loose earth, impregnated with copperas`r margin_note("[Copperas](https://en.wikipedia.org/wiki/Iron(II)_sulfate) is an iron sulfate, ferrous sulfate. [Ferric sulfate](https://en.wikipedia.org/wiki/Iron(III)_sulfate) is another sulfate of iron.")` that I have had: to pass by all this (I say) as for those vitriol stones, whereof we in England are wont to make our vitriol, I have seen, at the chief work where copperas is made, so great a variety of them, (many of which I have yet lying by me) that I could scarcely believe the workmen, when they affirmed them to be all copperas stones; and cannot but think it both very likely, that some of them contain other mineral substances besides vitriol, and very possible, that the saline parts of those stones, upon their solution by the rain, may work upon those other substances formerly concoagulated with them, and thereby imbue some parcels of the vitriol made of them with qualities other than are essential to the nature of vitriol, or belong ordinarily to it.
       

That there is also a difference between those bodies, that pass under the general name of common salt, cannot but be obvious to any chemist, that has occasion to make accurate trials on that subject.  And as for those concretes, that pass under the name of [salt-petre](https://en.wikipedia.org/wiki/Potassium_nitrate), there is probably no small disparity among them: for besides the difference which we have observed, and which is obvious enough between good English nitre [salt-petre], and that which is brought us over from Barbary, (which before it is much refined abounds very much with an incidental salt, that tastes much like sea-salt) besides this I say, those that do use both good European and good East-India salt-petre assure me, they find much difference between them, and give the preference to the latter.  And indeed I have often thought I discerned a considerable difference in the operations of several kinds of salt-petre even after purification: and probably that sort of salt-petre, which near London an ingenious man of my acquaintance does sometimes (but cannot always) make, chiefly of our sea-salt, has some differing qualities from that, which is drawn the common way out of the earth. And indeed salt-petre being but a kind of sal terrae [salt of the earth]; generated in very differently-qualified parcels of earth, may probably receive different qualities from the particular soil, wherein it grows, though these qualities lie concealed and unsuspected under the wonted exterior appearance of nitre.  Which consideration brings into my mind what was lately told me by a very ingenious gentleman, concerning one of the most eminent of our London physicians, who was wont, as this confidant of his assured me, as an excellent secret, to employ in some of his choice remedies that peculiar salt-petre, which he had drawn out of the earth dug up in church-yards. 
       
And such kind of differences would probably in other mineral bodies be taken notice of, if men's prepossessions did not make them ascribe the variations they meet with in their experiments, rather to any other cause, than the unsuspected difference of the materials employed about them.[^p]

[^p]: Why is there variation in chemical experiments? Boyle is suggesting that chemists' typical assumption is that materials are the same; so variation is due to other factors (e.g., as he has already mentioned, the position of the zodiac). This is a *theoretical* assumption, and Boyle believes it to be false This question is central to chemistry. ---RDM
       
Nor is it only, Pyrophilus, among mineral bodies of the same name, that such a diversity is to be found; but, if narrowly looked into, it is very probable, that a greater disparity may be discovered both among vegetables and animals, reputed of the same nature, than has been yet taken notice of.  Botanists indeed have exercised a commendable curiosity in sub-dividing plants of the same denomination, and few naturalists ignore, that there are (for instance) many sorts of roses, and of apples, which differ widely between themselves, as we see the difference between the red rose and the white, between the crab, the pippin, and the pearmain.  But besides these differences, which are obvious enough to be registered by botanical authors, there may be more undiscerned ones (which yet may be considerable ones) between the individuals of the same ultimate subdivision of plants, arising partly from the temperature of the air, which makes (for example) senna growing in England to differ much from that, which is denominated from Alexandria; partly from the nature of the soil, as is obvious in the change produced in wild simples transplanted into gardens; and partly from many other causes, which we have not now leisure to insist upon.  But we see oftentimes, that one rose much differs from another of the same kind, and one pearmain from another pearmain.  To which we may add, that the upper crust or surface of the earth being impregnated with subterranean exhalations of several sorts, and tempered with variety of juices, it may very possibly be, that some particular plant may attract such juice out of a determinate spot of ground, as may give it exotic qualities, and make it differ even from the neighbouring plants of the same kind: to which purpose I remember, that travelling many years since from Geneva towards Italy, I was in my passage through Switzerland by a gentleman of those parts (whose brother had been formerly my domestic assistant) invited to his castle, and entertained among other things with a sort of wine, which was very heady, but otherwise seemed to be sack`r margin_note("[Sack](https://en.wikipedia.org/wiki/Sack_(wine)) is a dry white wine formerly imported into Britain from Spain and the Canaries.")`; and having never met with any such liquor during my long stay in those parts, I was inquisitive to know whence it was brought: and being answered, that it grew amongst those mountains, I could not believe it, till they assured me, that growing on a little spot of ground, whose entrails abounded with sulphur, it had from the soil acquired its inebriating property, and those other qualities, which made it so differing from the wine of the rest of the vineyards of that country.  And now I mention wine, give me leave, Pyrophilus, to put you in mind of taking notice, what a great change is made in that liquor, when upon the recess of the spirits and more volatile sulphurous parts, or else the new texture they make with the others, it degenerates into vinegar; and yet how little either diminution of quantity or any other alteration doth appear upon this change to the beholder's eye.  And though nobody is likely to lose an experiment by mistaking vinegar for wine, because both those liquors and the changes of them are so familiar unto us---and because we are wont to taste each of them before we employ it---yet who knows what charges there may be in other bodies, with whose alterations we are unacquainted, though the eye, which is oftentimes the only sense employed about judging of them, discern no change in them? Such may daily be observed in the old seeds of plants, which, after their having been kept long beyond their due time, lose all their germinating power, without losing any of their obvious qualities.  And here let me further observe to you, that urine is made much use of, not only by dyers, but several other tradesmen, in many different operations (some of which we may elsewhere have occasion to treat of) belonging to their professions.  Now these men being wont to employ urine indiscriminately, without examining, whether it be rich in salt or not, and how long it has been kept, it may not be impertinent to take notice, that chemists, who have occasion to distil it often in great quantities, assure me, that they find a notable disparity between urines, that of healthy and young men abounding much more with volatile [salt](https://en.wikipedia.org/wiki/Salt_(chemistry)), than that of sickly or aged persons; and that of such as drink wine freely being much fuller of spirituous and active parts than that of those, whose drink is but beer or water.  But because the differing strength of urines, though it be very probable, is not so easily to be satisfactorily made out, we shall rather insist on this other observation confirmed to us by experience, which is, that though tradesmen are often wont to boil such and such things indifferently in any urine, as if it were all one how new or stale it is, they may sometimes thereby commit considerable errors.  For recent urine, wherein the saline parts are yet entangled among the rest, will allow itself to be boiled above one half or two thirds away, without the avolation of its volatile salt and spirits.  Whereas urine that has been many weeks kept, is liable to a putrefaction, whereby the cement (if I may so speak) of the ingredients that it consists of, perishing, or some change of texture occasioning their disjunction, (if not also concurring to produce them) the component parts fall asunder, and the saline particles extricating themselves from the rest, will even upon a very gentle heat (as trial made on purpose has informed us) fly away, and leave a phlegmatic and inactive liquor behind them.  In confirmation whereof I must acquaint you, Pyrophilus, with what lately befell me in reference to the distillation of urine: for having caused some of it to be buried in earthen vessels in a dunghill, to be there putrefied, for five or six weeks, I was by many occasional journeys kept from using it, until it had lain there between four and five months; and observing, when I caused it to be taken out, that the covers of the vessels had not been, by him I employed to put them in, well sealed, and besides were in some placed cracked, I suspected, that the heat of the dunghill had not only loosed the saline parts of the liquor, but driven them away: and accordingly by distilling it in a very gentle heat, and in a very high [cucurbit](https://en.wikipedia.org/wiki/Alembic), we obtained, instead of an active and saline spirit, a languid and nauseous phlegm.  And how great differences there may be between some experiments made with recent and putrefied urine, may be easily conceived by him who knows what operation salts have in the business of colours, and is acquainted with their efficacy in those other mechanical experiments, wherein urine is wont to be employed.  But I fear I have dwelt too long upon this theme, and therefore I shall proceed to the next.

`r margin_note("I am reminded here that I did my PhD work during the transition to LCD monitors from CRT monitors, and I was doing subliminal priming experiments that depended on displaying stimuli for a precise amount of time. Although LCDs and CRTs are both used as computer displays, they operate completely differently, and this difference turns out to affect how long the screen remains illuminated after something is shown. Jeff Rouder, Mike Pratte, and I spent a lot of time working out whether the new LCD monitors would be appropriate for our experiments (they were not, at the time. The effective refresh was too slow). ---RDM ")`
And in the third place, Pyrophilus, I shall observe to you, that there is a great difference to be found among many manufactured things, that pass under the same general name: which difference may proceed partly from that, which we have already observed to be found in the materials of which such factitious bodies are made, and partly from the way used in preparing them.[^r] To these heads many particulars may be reduced. But we shall at present restrain ourselves to the mention of two sorts of prepared bodies, namely, of such as are not purified and exalted enough, and of such as are so too much.

`r margin_note("Van Helmont was known for his work on kidney stones. He proposed both a cause, as Boyle describes, and a cure: the *Ludus helmontii*. [Alfonso-Goldfarb, A. M., Ferraz, M. H. M., \\& Rattansi, P. M. (2014). Seventeenth-century ‘treasure’ found in Royal Society archives: The Ludus helmontii and the stone disease. *Notes and Records of the Royal Society of London*, 68(3), 227–243.] Here, Boyle notes that a failure to replicate may be due to the replicators lack of knowledge about the procedure, but be blamed on the original experimenter. ---RDM")` And to begin with the first of these; it is very certain, that many chemical experiments delivered by sober authors have been believed false, only because the menstruums or other materials employed in the unsuccessful trials of them were not as highly rectified, or otherwise as exquisitely purified, as those that were used by the deliverers of those experiments; so that oftentimes the fault of a bad menstruum is injuriously imputed to a good artist.  That experienced chemist Van Helmont, in his paradoxical treatise of the [kidney] stone, endeavours (as we have elsewhere mentioned) to explicate the manner of its being generated, by the coagulation immediately ensuing upon the mixture of the two volatile spirits of urine and of wine.  This noble experiment has been by many unsuccessfully tried, and has been therefore by them discredited as a chemical fiction: and indeed the first, and I think the second time we attempted to make that coagulum, we found nothing at all of any such thing as we expected upon the mixture of the two aforementioned liquors; which though never so much shaken, and afterwards permitted to rest, did never in the least measure coagulate, which made us long suspect the experiment; until at length our favourable thoughts of that expert chemist making us think it possible, that the spirits we employed had not been sufficiently exalted, we dephlegmated some by more frequent, and indeed tedious rectifications (which yet proved but necessary) and then were satisfied by more accurate trials, that Helmont had not misinformed us.


       
So likewise the same author in his treatise *de Peste* ["the Plague"] much extolling, as a friend to the stomach, the entrails, the nervous parts, and even the head, the tincture or solution of amber made with spirit of wine [ethyl alcohol] (which medicine is indeed no ignoble one, when administered to constitutions, that can well bear the heat of it) many different physicians and chemists have attempted the preparing of this tincture with such bad success, that they have given out, that either Helmont delivered what was not true, or concealed some considerable circumstance of the process.
       
Whereas having digested sufficiently dephlegmed spirit of wine upon very finely powdered amber (which, if it be the higher-coloured, yields the deeper tincture) in a very gentle heat (for the neglect of which caution even expert artists have often lost their pains and glasses) we have several times had a good yellow tincture of amber, which was discernable in the menstruum both by the smell and taste; and to satisfy some, that suspected the tincture to proceed but from the exaltation of the menstruum itself by [digestion](https://en.wikipedia.org/wiki/Digestion_(alchemy)), and to manifest, that it was a real solution of the subtler parts of amber, we poured some drops of it into beer, or water, into which the spirit of wine suddenly diffusing itself, the dissolved amber was plainly discernible swimming like a thin film upon the surface of the liquor, whence, little by little, it steamed away into the air.
       
There is likewise, as we have tried, to be drawn with spirit of wine from pure [salt of tartar](https://en.wikipedia.org/wiki/Potassium_carbonate) a pretty high tincture, and of a taste, which I thought not unworthy the taking notice of: but having a while since tried to draw this tincture with spirit of wine, which (unknown to me) was much too weak for that purpose, after I had kept the glass a while in digestion, coming to look whether or not the spirit was tinged, I found, that the salt of tartar had drawn to itself and imbibed the aqueous particles of the spirit of wine, and being thereby (for a great part of it) dissolved into a liquor like that, which is commonly called [oil of tartar per deliquium](https://en.wikipedia.org/wiki/List_of_alchemical_substances), the subsiding salt was by the interposition of that saline liquor protected from the action of the spirit of wine; which being by this new way dephlegmed, would not mix with the saline liquor, but swam entirely above it.  To which I shall only add in general, that the German chemists are many of them so accurate in the rectification of their spirit of wine, that in England, where we are wont to be less careful about that particular, it is usual enough for those experiments of theirs to be unsuccessfully tried, wherein the alcohol of wine (as they call it) is requisite.
       
And as spirit of wine, so many other menstruums are made unfit for the perfecting of many real experiments, by their being too diluted.
       
Nor is it only, Pyrophilus, in menstruums, but in many other bodies, that the want of an exquisite depuration may produce in experiments variety of events.  As for instance, it has been complained of by sober men, that their preparations of silver, though never so carefully made, have been apt to produce violent vomits; whereas we have not observed a well-prepared medicine of duly refined silver to work emetically, even in women and girls, but by siege [laxative?] or urine.  But we cannot wonder at the violent operation of medicines made of ordinary silver: for not only that, which is coined, is wont, as the mint-masters themselves have confessed to me, to be allayed with sometimes about a twelfth part, sometimes a smaller or greater proportion of copper, for the greater convenience of the coin; but even that silver, which is commonly at great rates sold for refined silver, is not wont to be sufficiently freed from its copper.  Which I not long since manifested in the presence of one of our richest and most eminent refiners, by dissolving some of his purest silver in his own aqua fortis; for the greenness of the solution quickly betrayed the adherence of Venus `r margin_note("In alchemy, copper and lead were associated with the planets Venus and Saturn, respectively. ---RDM")` to the silver.  And no wonder, for I have seldom seen our best refiners blow off from their silver upon the test above half its weight of lead, whereas we think not our silver sufficiently refined for some purposes, till it have been freed from five or six times its weight of Saturn; and then it has sometimes afforded a solution almost as clear as water, with only now and then a light touch of sky-colour, but nothing near so high as the ceruleous [liquor that is supposed to be a true] tincture of silver, artificially separated from the rest of the body.

Now that ill effects by the mixture of copper may be produced in such medicines, as ought to be of pure silver, he that is acquainted with the violent emetic qualities of Venus can scarcely doubt. And as in men's bodies, so in other subjects, those experiments may easily deceive the artist's expectation, when he hopes to perform with silver and copper together those things, which suppose and require silver without copper, or any incidental metal: and as silver, so gold is very often employed for pure, when it is not so: for even the foliated gold, which is commonly sold here in England, however fine it is reputed, is not altogether free from the pollutions of other metals; for our gold-beaters, though for their own profit sake they are wont to use the finest coined gold they can get (as that which is capable of the greatest extension under the hammer) yet they scruple not to employ coined gold, and that the mint-masters (as themselves inform me) are wont to allay with copper or silver, to make the coin more stiff, and less subject to be wasted by attrition.  And as for those many goldsmiths and chemists, who think their gold most requisitely refined, when they have blown from it on the test a due proportion of lead, they may be therein sometimes mistaken: for though Saturn may carry away with him all the copper that devalued the gold, yet he does not likewise free it from the silver (for which purpose aqua fortis is therefore wont to be used) nay, the most skillful refiner that I ever yet knew, has several times affirmed to me, that [cupelling](https://en.wikipedia.org/wiki/Cupellation) fine gold with lead, the gold has after retained and protected from the fire a proportion of silver, that lay lurking in the lead, and was afterwards separated from the gold by aqua fortis, but in so small a quantity, that the experiment (the cost and pains considered) was not profitable.  And of this sort of instances, Pyrophilus, more might be presented, if we did not think tedium might be unwelcome to you.
       
But as many experiments succeed not according to expectation, because the menstruums employed about them were not pure enough; so some miscarry, because such menstruums are but too exactly depurated: for it is not so much the purity of liquors in their kind, as their fitness for the particular purpose, to which they are designed, that is in experiments to be principally regarded.  For instance, we have sometimes, for recreation sake, and to affright and amaze ladies, made pieces of white paper and linen appear all on a flame, without burning, singing, or as much as discolouring them.  This is performed by plunging the paper very thoroughly in weak spirit of wine, and then approaching it to the flame of a candle; by which the spirituous parts of the liquor will be fired, and burn a pretty while without harming the paper.  But if this experiment be tried with exquisitely rectified spirit of wine [less diluted alchohol], it will not succeed.  Of this phenomenon this plausible reason has been assigned, that the flame of the spirit of wine is so pure and subtle, that, like an ignis lambens`r margin_note("'Ignis lambens', or 'licking flame', appears to be a reference to static electricity. [See e.g. p57 in Knight (M.D.), T. (1749). Reflections upon catholicons, or universal medicines. With some remarks on the natural heat that is in animals, and the luminous emanations from human bodies. Also the sundry experiments and observations made upon the human calculus rationally consider’d, etc. T. Osborne.] ---RDM")`, it will not fasten upon the paper.  But experience has informed us, that this conjecture is but a mistake, for the flame of spirit of wine is so hot, that I have in lamp-furnaces employed spirit of wine instead of oil, and with the same flame I have not only lighted paper, but candles, and even melted foliated gold.  The true reason therefore, why that paper is not burned by the flame, that plays about it, seems to be, that the aqueous part [the water] of the spirit of wine being imbibed by the paper, keeps it so moist, that the flame of the sulphurous parts of the same spirit cannot fasten on it.[^s]  And therefore when the deflagration is over, you shall always find the paper moist; and sometimes we have found it so moist, that the flame of a candle would not readily light it.  And on the other side, having purposely made trials of plunging paper into sufficiently dephlegmated spirit of wine [that is, very pure alcohol], the paper not having aqueous moisture to defend it, was readily kindled and burned by the flaming spirit.   And one of our best ways to try the pureness of spirit of wine is grounded on this very supposition: for dipping it in a cotton-wick like that of a candle, and setting it on fire, if the flame fasten on the wick, it is a sign of the goodness of the spirit; but if it do not, we conclude it to be weak, and not sufficiently dephlegmed.  It has been likewise observed, that aqua fortis [nitric acid] will work more readily on lead, if it be diluted with water, than if it be purely rectified [[Why?](https://www.quora.com/Why-does-lead-only-react-with-a-very-dilute-nitric-acid-but-not-concentrated-nitric-acid)]. I elsewhere also mention an aqua fortis I have used, which was so strong, that it would not well dissolve silver itself, unless I first diluted it with fair water [[Why?](https://www.chemistryscl.com/reactions/reaction-of-silver-metal-dilute-nitric-acid/index.php)].  And within this very week, wherein I write these things, I have had an unwelcome proof, that liquors may by too exquisite a depuration be made unfit for our purposes.  For having to gratify some ingenious friends, made a certain menstruum, wherewith we had formerly done some things upon gold, which were (not altogether without cause) thought strange enough, we took care at this time to separate it from whatever was either of an aqueous or an earthy nature, more exactly than ever we had formerly done.  But coming to make use of this sort of menstruum, we found to our trouble and loss, that instead of performing its wonted operations upon gold better than before, we could do nothing at all with it: for it will not now by heat itself be brought to touch gold, though that metal were wont to be dissoluble in it even when cold.  And to satisfy you, that it was the too exquisite depuration of this liquor, especially from its terrestrial parts, that thus unfitted it to touch a metal, which is otherwise wont to melt as it were naturally in it without bubbling (almost like ice in lukewarm water:) we will subjoin, that not only we in vain tried to make it serviceable by weakening it with fair water; but having, for trial-sake, taken a little of this numerical parcel of liquor before it was so carefully rectified, we found, that it dissolved crude gold as well as we had reason to expect.  And it would be considered, whether or not in the extraction of the tinctures of several bodies, chemists do not only put themselves to a needless, but to a prejudicial trouble, when they refuse to employ any other spirit of wine, than that which is highly rectified.`r margin_note("Here Boyle is blaming failures to replicate on mistaken naïve theory: if X causes Y, then surely more concentrated X will be better at causing Y. This is not generally true. ---RDM")`  For, though in many bodies the parts desired by the artists being the sulphurous ones, the menstruum is the better for an exquisite dephlegmation; yet in many other concretes the useful and efficacious parts have in them something of saline, which makes them more free to impregnate copiously such liquors, as have some aqueous mixed with their sulphurous parts.
        
[^s]: This is still a common [party trick](https://www.youtube.com/watch?v=nj5jnjlPLuk). Boyle's explanation is correct. ---RDM

But because there is nothing more easy than by diluting spirit of wine, though never so strong, to make it as weak as one pleases; and because pure spirit of wine is that of all other menstruums, the chemists generally make most use of, and which costs them most of charge and trouble (insomuch that here in London that which is perfectly dephlegmed is valued, in their shops that sell both, at ten times the price of common spirit of wine) I presume you will not take it ill, that without being obliged to it by the title of this discourse, I take this occasion to acquaint you with my method to obtain dephlegmed spirit of wine; especially since the practice of the common way of frequent rectifications is (not to mention other inconveniences) wont to prove either exceeding tedious, or insufficient.`r margin_note("Or: Boyle's idiotproof recipe for purer ethyl alcohol. ---RDM")` Put then about an inch thick of [tartar calcined to whiteness](https://en.wikipedia.org/wiki/Potassium_carbonate) (for I find it not necessary to reduce it to a salt) and very dry, into the bottom of a tall and slender glass body, and pour on it as much spirit of wine, that has been but once rectified, as will, when they have been shaken together, swim above the tartar a finger's breadth (more or less in proportion to the tartar you put in) and then the head and receiver being carefully fastened on again, in a gentle heat draw off the spirit of wine, shifting if you please the receiver`r margin_note("Perhaps shifting the receiver causes the purified, condensed alcohol to flow into a waiting container? ---RDM")`, when about half is come over, and if need be, rectifying once more all that you distil upon dry calx of tartar as before.  Whether or not you may meet with this method in some chemical books, I know not:`r margin_note("Boyle has knowledge that he does not think is widespread among other researchers, and this knowledge would increase the quality of research by giving researchers a way of reliably making one of their most important materials. ---RDM")` but it seems, that either it has not been clearly taught, or has been proposed by distrusted authors, or else among other processes, by being found in whose company it has been discredited.  For the most ancient and experienced distillers I have met with, have either contented themselves to follow the common way of repeated rectifications, though thereby they lose much time, and much spirit of wine; or else have had recourse to peculiar vessels of such a height, as besides that they are neither easily nor cheaply to be procured, do not, as far as I have hitherto seen, excuse the need of reiterated rectifications.  Whereas, when we considered, that the fixed salt of tartar readily imbibes aqueous bodies, and that yet it will not at all mix with pure spirit of wine, it was easy to conclude, that the phlegmatic part of the spirit of wine would be soaked up by the alcalizate salt, whereby the inflammable part would be freed from it.`r margin_note("Because 'spirit of wine' is water and alcohol, Boyle believes that the potassium carbonate absorbs the water and other impurities, leaving the alcohol freer to evaporate. ---RDM")`  And accordingly when we proceeded after the manner above prescribed, we found, that the liquor, that was produced upon the first rectification from the salt, being fired in a warm silver-spoon, did not leave behind it one drop of phlegm, or so much as the least moisture upon the spoon; nay, and indeed did endure a closer examination, to which for curiosity's sake we thought fit to put it.  And when the distillation was carefully made, we found by frequently (for trial-sake) shifting the receiver, that all the spirit that ascended was (to sense) equally pure, since that which came up last of all, even till the calx seemed to begin to grow dry, by beginning to cleave at the top, did burn all away, as well as that which came over first.  And having for further trial taken out the calcined tartar, and distilled it with a good fire, it yielded us pretty store of a nauseous and strongly scented liquor, which seemed to be but phlegm, both to the taste, and by its not being at all inflammable, though carefully tried.  The same calx of tartar being kept in some earthen vessel upon the fire till it be well dried, which will require a good heat, may be employed more than once in this operation.  And it was not needlessly that we prescribed bodies tall and slender; for we found that the experiment did not succeed in large and low ones, and much less in retorts, in which the phlegm is wont to rise together with the spirit; yet we found, that provided the distillation were made with a sufficiently mild heat, a glass, though very broad, and but moderately high, would serve the turn so far, as that the first half that ascended (the other being very weak) proved a spirit, that in a silver-spoon would burn perfectly all away.  And because white calx of tartar is sometimes not so easy to be procured, we will add, that we have for trial-sake sometimes substituted [quick-lime](https://en.wikipedia.org/wiki/Calcium_oxide), or salt of [pot-ashes](https://en.wikipedia.org/wiki/Potash) (made by a single solution, filtration and coagulation) with no bad success, especially in case of removing the receiver before the ascension of the last part of the liquor, though even that itself has sometimes from quick-lime come up inflammable enough.  And therefore this alcohol of wine we peculiarly call the alcalizate spirit of wine; and the rather, because spiritus vini tartarizatus, which perhaps may be thought the best name for it, is employed by eminent chemical writers to signify a different thing.  And a practicable way of making such an alcalized and pure spirit of wine we thought not unfit to teach you here once for all, in regard the menstruum is so highly useful, not only for tinctures, extracts, and many other chemical operations, but in the making of many different philosophical experiments, and particularly some of those, which you may meet with in our writings.`r margin_note("Public knowledge of lab procedures is important for reproducibility. Without this knowledge, as Boyle points out, the reader may try some of the experiments he describes, but fail without understanding why. ---RDM")`  And an eminently ingenious person (but to me a stranger) chancing to get a sight of this essay, was pleased to give me thanks for this last part of it; because, though he had very often made use of salt of tartar to improve spirit of wine, yet he did it before, not to dephlegm the weaker liquor, but to sharpen the strong with the alcali: which though I deny not to be a thing feasible, yet (as I told him) unless it be skilfully attempted, the highly rectified liquor, that is poured on, will rather leave some of its most spiritous parts behind, than carry up so fixed a salt.
       
